### ISSUE TITLE
superagent-retry plugin is no longer necessary

### ISSUE THREAD

**Issue by rifflock** [segmentio/analytics-node#100]
Hi!

I hit this issue segmentio/superagent-retry#24 when working with this module, and when I dug deeper I found that the need for superagent-retry module seems to have been removed by visionmedia/superagent#1155 where they incorporate the retry logic directly into superagent.

Since segmentio/superagent-retry#24 has been open since January with no traction, and since it seems like it's no longer _really_ necessary anymore, I put together a PR to remove reliance on it.

If there's interest I could create another PR to [superagent](https://github.com/visionmedia/superagent) to allow for more customization for retry logic as was mentioned in the [comments](https://github.com/segmentio/superagent-retry/issues/24#issuecomment-275824874)

**Comment by rifflock** [comment]
I'm not sure what's going wrong with the pull request that it's not triggering the CircleCI build. I rebased to master and created a new PR with my changes on a fresh commit, so hopefully that works.

**Comment by vadimdemedes** [comment]
I suspect it's the way Circle CI works. It tests PRs from local branches which belong to the repository itself, but ignores PRs from forks. If that's indeed true, it's really disappointing and we might have to switch back to Travis, which doesn't have that flaw.

**Comment by vadimdemedes** [comment]
New release is out - https://github.com/segmentio/analytics-node/releases/tag/v3.0.0.
