### ISSUE TITLE
Flush timer is not cleared when manually flushing queued events.

### ISSUE THREAD

**Issue by justin-summerlin** [segmentio/analytics-node#102]
This came up when using this library inside an AWS Lambda function. I noticed that there was always a ~10 second delay before the function would close (without forcing Lambda to finish without waiting on the event loop). After debugging a bit I noticed the problem was caused by the timer being set in `Analytics.prototype.enqueue` which defaulted to 10000 ms not being cleared in `Analytics.prototype.flush`.

**Comment by justin-summerlin** [comment]
It looks like this will be fixed by https://github.com/segmentio/analytics-node/pull/54.

**Comment by vadimdemedes** [comment]
Yes, #54 should fix it.

**Comment by vadimdemedes** [comment]
#103 (previously #54) is merged now, which fixes this issue. Keeping it open until a new release is out.

**Comment by vadimdemedes** [comment]
New release is out - https://github.com/segmentio/analytics-node/releases/tag/v3.0.0.
