### ISSUE TITLE
No release notes

### ISSUE THREAD

**Issue by danconnell** [segmentio/analytics-node#115]
You recently removed the History.md file (https://github.com/segmentio/analytics-node/commit/701b893482c7507bf8d5cfd920532d84f0180638) in favour of GitHub release notes.

However, release v3.0.0 has no release notes. For a major version change, this makes it very difficult to judge what was changed.

Can you please provide release notes for v3.0.0 and for releases in the future?

**Comment by stephenmathieson** [comment]
/cc @stevenmiller888 

also, @vadimdemedes i was worried about this :p

**Comment by stevenmiller888** [comment]
Released v3.0.0 this morning and @vadimdemedes was going to add release notes tonight. We should have timed it better to not have the gap. Sorry about that!

**Comment by vadimdemedes** [comment]
Yes, as @stevenmiller888 said, I was going to add release notes the next day. I guess @stevenmiller888 and me were just too excited and released sooner than we should've had 😃

**Comment by vadimdemedes** [comment]
Added release notes at https://github.com/segmentio/analytics-node/releases/tag/v3.0.0.

**Comment by danconnell** [comment]
Thanks!
