### ISSUE TITLE
Method calls hang forever if the underlying request to the Segment server never completes.

### ISSUE THREAD

**Issue by serhalp** [segmentio/analytics-node#119]
If the [request to the `/v1/batch` endpoint](https://github.com/segmentio/analytics-node/blob/4290503572a7c9661661dbcafef75b573cdbda0b/index.js#L225-L237) on the Segment server never completes, the corresponding call to `track()` or `identify()` (etc.) hangs forever and never calls the passed callback with an error / never rejects the promise.

There is currently no way to configure a timeout with this module. In my opinion an abstracted plug-and-play client library for a specific service such as this one should enable retries and timeouts by default and allow configuration.

The underlying request library you're using, superagent, [supports timeouts but they are not enabled by default](http://visionmedia.github.io/superagent/#timeouts). I'll open a PR in a few minutes to allow opting in to timeout functionality. Again, I think it should enabled by default, but that's your call and I'm not sure what the default timeout value should be.

FYI as I understand it the superagent module will retry on timeout errors if it is configured to retry. :+1:

Thank you!

**Comment by serhalp** [comment]
cc @bobzoller @sylspren

**Comment by stephenmathieson** [comment]
If our API isn't responding, we've got huge problems on our hands! Is this something you're running into frequently? If so, please contact our support team!

That said, configurable timeouts/retries sound great to me!

**Comment by serhalp** [comment]
@stephenmathieson Thanks for your concern. It's occurred twice in two weeks. But (back of the envelope) we've likely made on the order of ~200M tracks in that span (from this worker of this service alone). I think 99.9999995% of requests responding eventually is very reasonable. Totally happy with just having the client lib time out and retry 0.000001% of the time. :)
