### ISSUE TITLE
Timer is scheduled to flush even if queue is empty

### ISSUE THREAD

**Issue by chris-pardy** [segmentio/analytics-node#121]
At the end of the enqueue method a timer is started to flush the queue. However if the queue has already reached the flushAt length this is not necessary.

Even if this behavior is expected we'd like a mechanism to turn off the timer based flushing since we're running on lambda and want to more aggressively flush.

**Comment by f2prateek** [comment]
Tracking internally https://segment.atlassian.net/browse/LIB-119.

A workaround for now seems to use a really high value for your timer? I'm not sure what the downside of starting the timer is - it seems harmless in this case.

**Comment by chris-pardy** [comment]
@f2prateek our primary issue with starting the timer is that the lambda runtime waits until the event loop is empty before sending the response to a request. Since the timer is left in the event loop this timer was adding several seconds to our response time.

**Comment by AWzone** [comment]
Having the same issue with Lambda. Flush timer causes node to hang and not respond to the next request. The observed result is that every other Lambda request times out unless you set the lambda timeout really high (10 s).

**Comment by penkeysuresh** [comment]
Along with the above setting, do note that `context.callbackWaitsForEmptyEventLoop` parameter should be set to `true` (default value). If it's not set to true, Lambda will go into frozen state, and it may result in missing events if AWS Lambda chooses not to use the frozen process the next time lambda gets invoked. Do refer to the [documentation](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-prog-model-context.html) for more details

**Comment by f2prateek** [comment]
The `flushInterval` is very much documented and part of the public API. Documented both here https://github.com/segmentio/analytics-node/blob/master/index.js#L25 and https://segment.com/docs/sources/server/node/#configuration.

**Comment by f2prateek** [comment]
I think that should be fine, I would love to have a few folks using lambda confirm that this approach works though.

**Comment by chris-pardy** [comment]
@f2prateek opened PR #172 for this issue. Can't seem to add reviewers.

**Comment by chris-pardy** [comment]
@AWzone @penkeysuresh could you guys take a look at the PR, and maybe help with testing it.

**Comment by penkeysuresh** [comment]
@chris-pardy sorry for the delay, we went ahead with segment [http api](https://segment.com/docs/sources/server/http/) for our use case with Lambda. Using a queue inside Lambda didn't make sense for us.

**Comment by stabilemobile** [comment]
I've run into this issue as well when using the SDK in a Lambda environment – we work around it by explicitly calling `flush()` when done enqueueing , since per the source ( https://github.com/segmentio/analytics-node/blob/master/index.js#L235-L238 ) it seems that the `flush` method clears any existing interval timer.

I think it would make sense to have some way to disable the flushInterval, maybe by setting to null in the config.

**Comment by simonprickett** [comment]
I wasted a lot of time wondering what was going on with Lambda and the Node API today before stumbling on this issue.  Eventually I stopped using the Node API and made a HTTP call directly instead.

**Comment by uccmen** [comment]
followed the footsteps of @penkeysuresh & @simonprickett after spending a lot of hours debugging the intermittent case of event delivery failure to segment using the node api.

**Comment by himanshu-onscale** [comment]
I'd like to echo some of the comments made here. I attempted to follow the methods laid out here by setting the flushInterval and flushAt parameters and manually calling flush() but event tracking was still inconsistent compared to the standard HTTP API.

**Comment by leonkyr** [comment]
Calling flush manually is not optimal and reliability is important here..
