### ISSUE TITLE
Replace superagent with a different request library

### ISSUE THREAD

**Issue by stephenmathieson** [segmentio/analytics-node#124]
There's been a lot of discussion surrounding this in the past. We need a library that works both client-side and server-side, supports being browserified, doesn't expose globals (`isomorphic-fetch`) and doesn't break the current API.

Currently our tests are failing due to a security vulnerability in superagent:

- https://nodesecurity.io/advisories/479
- https://github.com/visionmedia/superagent/issues/1259

I may be able to own this and get it handled in the next day or so, depending on how urgent we feel this vulnerability is.

Any suggestions for replacement libraries?

/cc @stevenmiller888 @nettofarah @vadimdemedes

**Comment by vadimdemedes** [comment]
Looks like axios is a good fit here! I personally use `got`, but it doesn't have a browser version. Little tip, use `isomorphic-unfetch` instead of `isomorphic-fetch` to save a lot of bytes on the client. It uses extra small https://github.com/developit/unfetch.

**Comment by nettofarah** [comment]
I like axios a lot.
I think their middleware/interceptor feature can help add a lot of cool extra features.

**Comment by stephenmathieson** [comment]
I've seen `isomorphic-unfetch`, it's pretty great!

Sounds like axios is the winner =]

**Comment by nettofarah** [comment]
We can use this sweet library on our tests if we go with axios: https://github.com/nettofarah/axios-vcr

**Comment by stephenmathieson** [comment]
Woah Netto, that's a sweet library! We should hire the guy who wrote it!

**Comment by nettofarah** [comment]
I'll send him this job description: https://segment.com/jobs/525952-Product-Engineer
