### ISSUE TITLE
3.1.0 causes no data to be sent to segment

### ISSUE THREAD

**Issue by chaserelock** [segmentio/analytics-node#127]
On node v8.2
Track & Identify calls fire fine on version 3.0.0
After upgrading to 3.1.0 (due to a ^3.0.0 package.json setting and a deployment that didn't honor yarn.lock), no events came from our production source.

The beginning of this discussion (for more context) was had with Andy Yeo (success engineer)

**Comment by stephenmathieson** [comment]
@chaserelock I'm looking into this now. Surely a bug on our part. Apologies!

**Comment by stephenmathieson** [comment]
Looks like I forgot to pass the write key to the API. I'm hugely embarrassed. I'll push a hotfix immediately.

**Comment by stephenmathieson** [comment]
@chaserelock `3.1.1` should fix this issue. I've run some extensive tests locally and all events seem to make it into my debugger.

I've filed a SEV at Segment and we take these sorts of outages very seriously. We're in obvious need of better testing here, which I'll be adding to my plate immediately.

Once again, my apologies for this. This could have very easily been caught in tests, but wasn't.

**Comment by chaserelock** [comment]
Thanks for the fix @stephenmathieson -- glad it was caught sooner than later
