### ISSUE TITLE
Doesn't work with Create React App's build script

### ISSUE THREAD

**Issue by denkristoffer** [segmentio/analytics-node#142]
Hi 👋 

At the moment, `analytics-node` doesn't work with [Create React App](https://github.com/facebookincubator/create-react-app), as the build script fails when trying to minify the ES6 code (https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify). I'd like to hear if you'd be willing to publish a pre-compiled version?

I understand that this is a node library and perhaps not meant to be used in the browser, but the `analytics.js` package on NPM is outdated, so please correct me if I'm wrong, but `analytics-node` seems like the only way to use Segment if you want to load it through a module.

**Comment by vadimdemedes** [comment]
Hey, could you elaborate on why analytics.js isn't suitable for you?

**Comment by denkristoffer** [comment]
I was hoping to use a way that would work in react-native as well.

**Comment by vadimdemedes** [comment]
Is your app ejected?

**Comment by denkristoffer** [comment]
No, it is not.

**Comment by f2prateek** [comment]
> I'd like to hear if you'd be willing to publish a pre-compiled version?

@denkristoffer do you have examples of how other libraries publish both compiled and pre-compiled versions? We might be able to take this on depending on how easy it is.

For the browser, I would definitely still recommend using analytics.js because of the reasons in https://github.com/segmentio/analytics-node/issues/139#issuecomment-352983852

**Comment by vadimdemedes** [comment]
We can use https://github.com/developit/microbundle for that.

**Comment by denkristoffer** [comment]
Looks like CRA will [be compiling dependencies with babel-env in the next major release](https://github.com/facebookincubator/create-react-app/pull/3776).

**Comment by zeeshanjan82** [comment]
As I understand we need to use analytics.js in react app or in any single page app but then do we need to really rely on window.analytics there doesn't seem to be any example available to use analytics.js with a single page app as we cannot use the code snippet directly in index.html that will only work on index.html not on other routes.

**Comment by denkristoffer** [comment]
I haven't been able to find a reliable way to ensure analytics.js is ready to use in a React app. Right now I'm doing it in a horrible way by looking for `window.analytics` and then using `setTimeout()` periodically if it's not found.

Would appreciate some input on how to do this until we can use `analytics-node` in our app.

**Comment by hzhu** [comment]
> Also, another thought on why you might prefer analytics-node over analytics.js is that it's hard to ensure window.analytics is loaded, while with the npm module you can be sure. (Any thoughts on this?)

Hiyo @denkristoffer, the proper way to setup `analytics.js` in create-react-app is to put the script inside the `<head>` element of your document; load it with your Segment API key which is referenced through  a [custom environment variable](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-custom-environment-variables):

1) First, create an `.env` file in the root of your project which contains your API key. Your `.env` should look like this:
```
REACT_APP_SEGMENT_API_KEY=<Insert your Segment API key here>
```

2) Then put the `analytics.js` snippet in the `<head>` of your `public/index.html` and load the script using your API key which is [referenced](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#referencing-environment-variables-in-the-html) through custom environment variables:
```html
<script type="text/javascript">
  !function(){var analytics=window.analytics=window.analytics||[];if(!analytics.initialize)if(analytics.invoked)window.console&&console.error&&console.error("Segment snippet included twice.");else{analytics.invoked=!0;analytics.methods=["trackSubmit","trackClick","trackLink","trackForm","pageview","identify","reset","group","track","ready","alias","debug","page","once","off","on"];analytics.factory=function(t){return function(){var e=Array.prototype.slice.call(arguments);e.unshift(t);analytics.push(e);return analytics}};for(var t=0;t<analytics.methods.length;t++){var e=analytics.methods[t];analytics[e]=analytics.factory(e)}analytics.load=function(t,e){var n=document.createElement("script");n.type="text/javascript";n.async=!0;n.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.com/analytics.js/v1/"+t+"/analytics.min.js";var o=document.getElementsByTagName("script")[0];o.parentNode.insertBefore(n,o);analytics._loadOptions=e};analytics.SNIPPET_VERSION="4.1.0";
  analytics.load("%REACT_APP_SEGMENT_API_KEY%");
  analytics.page();
  }}();
</script>
```

**Comment by mbifulco** [comment]
Hey @hzhu - thanks for the reasonable workaround.  I'm going to give that a shot for my project.  It does seem like there are a few downsides.  I'm wondering if there's going to be a supported path for using the node module with CRA in the future.

- from a developer experience, I lose the nice autocomplete hints that VSCode provides for dependencies installed through npm:
![image](https://user-images.githubusercontent.com/1844496/43251911-2c322b7e-90b9-11e8-9d32-502e0ff08bc8.png)

- accessing `window` is tricky on apps that have Server Side Rendering set up - on the server side, `window` is not generally available.  This means that my code has to check to see if `window` exists before I run any segment calls.

**Comment by f2prateek** [comment]
Please keep in mind that you are sort of comparing apples and oranges when comparing analytics-node in the browser to analytics.js and are giving up a lot of functionality.

Analytics.-node fits into this relatively tiny ~300 line file https://github.com/segmentio/analytics-node/blob/master/index.js

Analytics.js by contrast looks like this for segment's public facing site https://cdn.segment.com/analytics.js/v1/zaySL4FGIiLsxt3I7omU5uLxXqxaBMPh/analytics.js

**Comment by notmessenger** [comment]
Piggy-backing off of @mbifulco's comment you also need to check for whether or not `analytics.js` has finished loading, as well as configuring all of the plugins.  Otherwise your call to it may fail as well in the browser if the call is made before it is available.  This is the code I put in place to address this.

_/public/index.html_

```js
  // the normal loading code
  analytics.ready(function() {
      window.isSegmentReady = true;
    });
  }}();
```

_/src/services/Analytics/index.js_

```js
/**
 * @module
 *
 * Capture page views, events, and errors for aggregation in segment.com
 */

/**
 * Capture page views, events, and errors for aggregation in segment.com
 *
 * For any method you want to provide as the API to this class you need to create two methods.
 * The first method is the public API you wish to expose (e.g. page()) which calls the second method.
 * The second method should be designated as async.  It should call isReady() and then execute its
 * logic if the call returns true (e.g. _page()).  The reason for this is because segment.io's code
 * is loaded into the browser environment asynchronously and then goes through an initialization process
 * with/for each plugin enabled for the integration.  This takes an indeterminate amount of time to complete,
 * during which this code is likely already being called.   It will fail without segment.io being available to
 * be called.  There are also environments that will not ever load segment.io - such as testing and server side
 * rendering (SSR) - but for which this code will still be called.  This approach also manages for these
 * environments.
 *
 * @class
 */
export class Analytics {
  constructor() {
    /**
     * Determiniation on whether or not analytics.js is in a state of readiness.
     *
     * @type {?Boolean}
     */
    this.isSegmentReady = null;
  }

  /**
   * Check whether the flag set in segment.io's analytics.ready() call in /public/index.html has been set.
   *
   * This class may be called before it is ready so this checks for it via a number of timeouts.
   * If it becomes set during this time it returns its value, otherwise returns rejected promise.
   *
   * @private
   * @returns {Promise}
   */
  checkIfReady() {
    return new Promise((resolve, reject) => {
      let counter = 0;

      const checkIsSegmentReady = function() {
        if (counter === 50) {
          reject(`segment.io is not ready`);
        } else {
          if (window.isSegmentReady) {
            resolve(window.isSegmentReady);
          } else {
            counter++;
            window.setTimeout(checkIsSegmentReady, 25);
          }
        }
      };

      checkIsSegmentReady();
    });
  }

  /**
   * Capture bare message or error object as event
   *
   * @param {String|Object} error
   * @see {@link https://docs.sentry.io/learn/capturing/?platform=browser}
   * @returns {undefined}
   */
  error(error) {
    this._error(...arguments);
  }

  /**
   * Capture bare message or error object as event if segment.io is ready
   *
   * @param {String|Object} error
   * @see {@link https://docs.sentry.io/learn/capturing/?platform=browser}
   * @private
   * @returns {undefined}
   */
  async _error(error) {
    const isReady = await this.isReady();

    if (isReady) {
      window.Raven[typeof error === 'string' ? 'captureMessage' : 'captureException'](error);
    }
  }

  /**
   * Associate users and their actions to a recognizable user id and traits
   *
   * @param {?String} userId
   * @param {?Object} traits
   * @param {?Object} options
   * @param {?Function} callback
   * @see {@link https://segment.com/docs/sources/website/analytics.js/#identify}
   * @returns {undefined}
   */
  identify() {
    this._identify(...arguments);
  }

  /**
   * Associate users and their actions to a recognizable user id and traits if segment.io is ready
   *
   * @param {?String} userId
   * @param {?Object} traits
   * @param {?Object} options
   * @param {?Function} callback
   * @see {@link https://segment.com/docs/sources/website/analytics.js/#identify}
   * @private
   * @returns {undefined}
   */
  async _identify() {
    const isReady = await this.isReady();

    if (isReady) {
      window.analytics.identify(...arguments);
    }
  }

  /**
   * Whether or not analytics.js is in a state of readiness.
   *
   * @see {@link https://segment.com/docs/sources/website/analytics.js/#ready}
   */
  async isReady() {
    if (this.isSegmentReady === null) {
      this.isSegmentReady = await this.checkIfReady();
    }

    return this.isSegmentReady;
  }

  /**
   * Record page views
   *
   * @param {?String} category
   * @param {?String} name
   * @param {?Object} properties
   * @param {?Object} options
   * @param {?Function} callback
   * @see {@link https://segment.com/docs/sources/website/analytics.js/#page}
   * @returns {undefined}
   */
  page() {
    this._page(...arguments);
  }

  /**
   * Record page views if segment.io is ready
   *
   * @param {?String} category
   * @param {?String} name
   * @param {?Object} properties
   * @param {?Object} options
   * @param {?Function} callback
   * @see {@link https://segment.com/docs/sources/website/analytics.js/#page}
   * @private
   * @returns {undefined}
   */
  async _page() {
    const isReady = await this.isReady();

    if (isReady) {
      window.analytics.page(...arguments);
    }
  }

  /**
   * Reset user id and clear traits
   *
   * @see {@link https://segment.com/docs/sources/website/analytics.js/#reset-logout}
   * @returns {undefined}
   */
  reset() {
    this._reset(...arguments);
  }

  /**
   * Reset user id and clear traits if segment.io is ready
   *
   * @see {@link https://segment.com/docs/sources/website/analytics.js/#reset-logout}
   * @private
   * @returns {undefined}
   */
  async _reset() {
    const isReady = await this.isReady();

    if (isReady) {
      window.analytics.reset();
    }
  }
}

const AnalyticsService = new Analytics();

export default AnalyticsService;
```

usage:

```js
import Analytics from 'services/Analytics';

class Component extends ReactComponent {
  constructor(props) {
    super(props);

    this.title = 'Secure Login';
  }

  captureAnalytics() {
    Analytics.page('Authentication', this.title, {
      title: this.title,
    });
  }

  componentDidMount() {
    this.captureAnalytics();
  }
}
```


As noted in the comments of the Analytics service this setup also addresses situations in which Segment is not available, such as testing, SSR, or when it is blocked by the browser.

**Comment by pooyaj** [comment]
Closing as stale
