### ISSUE TITLE
Upgrade guide for 2.0 -> 3.0

### ISSUE THREAD

**Issue by bradvogel** [segmentio/analytics-node#160]
Hi - we're looking at upgrading to 3.0 and it's not immediately clear what the breaking API change was. From the History.md file, it looks like it was just `Rename flushAfter to flushInterval (#112)`? If that's true, can you add a small section under the 3.0 release that says `The only breaking API change is that flushAfter is now flushInterval. No other API changes were made`. This will make it much more clear on what needs to be done to upgrade to 3.0. Thanks!

**Comment by f2prateek** [comment]
The changes are documented here https://github.com/segmentio/analytics-node/releases/tag/v3.0.0
