### ISSUE TITLE
events malformed when sending to mailjet

### ISSUE THREAD

**Issue by mavrick** [segmentio/analytics-node#161]
I've hit a brickwall trying to get support out of mailjet and they keep copy/pasting the same response. 

We are seeing missing users and event data within mailjet when sending from node/web via segment. It is being caused by malformed JSON being generated and sent to mailjet. The request to segment is successful because we are seeing the events show up in amplitude and vero.

**Comment by f2prateek** [comment]
hey @mavrick, have you tried reaching out to our support at https://segment.com/help? They can help you debug and route it to the appropriate team as needed (generally this issue would be covered by our destinations team).
