### ISSUE TITLE
Can this library be used in Vue projects ?

### ISSUE THREAD

**Issue by xerosanyam** [segmentio/analytics-node#165]
I am searching for a way to easily add analytics library to vue components

**Comment by tbeseda** [comment]
I think Analytics.js would be best for a front end project: https://segment.com/docs/sources/website/analytics.js/quickstart/
This library is for server-side Node work.

**Comment by f2prateek** [comment]
@tbeseda agreed! while analytics-node can be used in the browser, I would highly recommend using a.js.
