### ISSUE TITLE
"Couldn't find package \"@segment/loosely-validate-event@^1.1.2\" required by \"analytics-node\" on the \"npm\" registry.".

### ISSUE THREAD

**Issue by crotten** [segmentio/analytics-node#167]
I am trying to install this package via yarn and am getting the following error message: ```An unexpected error occurred: "Couldn't find package \"@segment/loosely-validate-event@^1.1.2\" required by \"analytics-node\" on the \"npm\" registry.".```

**Comment by f2prateek** [comment]
Probably a bug in Yarn or NPM? The versions are visible here https://www.npmjs.com/package/@segment/loosely-validate-event

**Comment by crotten** [comment]
Thank you for your response.  I finally figured out what the issue was.  We have a private repo that we use for our company and my .npmrc file was setup to use that and required auth all the time which was causing the issue when trying to install the @segment package.
