### ISSUE TITLE
🇪🇺 GDPR: Delete User

### ISSUE THREAD

**Issue by vhmth** [segmentio/analytics-node#169]
Per GDPR announcement, it'd be good to have the `/delete` call be implemented here. :-)

https://segment.com/blog/segment-and-the-gdpr/

**Comment by sperand-io** [comment]
Let us know your thoughts and whether that makes sense— will leave this open until we get your take!

**Comment by f2prateek** [comment]
```
    const req = {
      method: 'POST',
      url: `${this.host}/v1/batch`,
      auth: {
        username: this.writeKey
      },
      data,
      headers
    }

    if (this.timeout) {
      req.timeout = typeof this.timeout === 'string' ? ms(this.timeout) : this.timeout
    }

    axios(req)
      .then(() => done())
      .catch(err => {
        if (err.response) {
          const error = new Error(err.response.statusText)
          return done(error)
        }

        done(err)
      })
```

**Comment by f2prateek** [comment]
(whoops, sorry for closing, my mistake)

**Comment by vhmth** [comment]
👋 @sperand-io good to meet on another social platform! 🐦🐈

This is what I'm doing currently that's resulting in a 404:

```
new Promise((resolve, reject) => {
  request({
    url:    'https://api.segment.io/v1/delete',
    method: 'POST',
    auth:   { user: segmentWriteKey, pass: '' },
    body:   { userId },
    json:   true
  }, (err, response) => {
    const { statusCode } = response;

    if (err) {
      return reject(err);
    } else if (statusCode >= 400) {
      return reject(new Error(`bad segment user delete request: ${statusCode}`));
    }

    resolve();
  });
})
```

My guess is because I'm not doing what's laid out in the `Authentication` section of what you linked. However, I'm a bit confused about that section, specifically this:

> Authentication
> The mutation above requires a valid access token in the Authentication request header, which you can generate using the credentials of any workspace owner.
> 
> In order to fetch an access token, you simply issue a mutation like the one above with the following structure:

**Comment by f2prateek** [comment]
I think the 404 is because the request is incorrect. Here's the example in the docs. Note that this is a GraphQL API - not a REST API and lives at `https://gdpr.segment.com/graphql`:

```
req
    .fetch({
      query: mutation {
          createWorkspaceRegulation(
            workspaceSlug: &quot;workspace-slug&quot;
            type: SUPPRESS_AND_DELETE
            userId: ${req.params.userId}
          ) { id }
        }
    })
    .then(res => {
      console.log(res)
    });
```

**Comment by vhmth** [comment]
@f2prateek Is there any way to do a request w/o GraphQL? I'd rather not pull in GraphQL just for this call if possible.

**Comment by f2prateek** [comment]
You don't need to - the example in the docs is using plain old http but with a graphql query in the body.

See the "Making requests with GraphQL" section in https://segment.com/docs/guides/best-practices/user-deletion-and-suppression/

**Comment by vhmth** [comment]
@f2prateek @sperand-io a couple of things (sorry about the late reply here - just got back from vacation):

1. I'm using a write key - the same one Segment supplies me. Is there another write key that needs to be generated? Looking at the `Authentication` section [here](https://segment.com/docs/guides/best-practices/user-deletion-and-suppression/), it seems like I'd need to login and use a short-lived token otherwise to make each individual deletion request? That seems like overkill to me - really looking for something easy like reusing the write key I give the segment node lib or generating a new one.

2. All of your documentation is very GraphQL-specific. You can't expect your users to be using GraphQL or understand what anything means in your docs [here](https://segment.com/docs/guides/best-practices/user-deletion-and-suppression/). Also, the `createWorkspaceRegulation` function is used for every request (including the HTTP request example), but there is nothing in the documentation that tells me what this function is actually spitting out.

The bottom line here is that these APIs are going to be extremely important for Segment's customers to ensure they are protecting their bottom line. Under the GDPR, you can get fined a cap of 10% of global revenue or 10M Euros (whichever is greater) if you don't properly comply.

This responsibility falls squarely on the laps of Segment's customers, so I'd hope for a better API since Segment is primarily used as such. I understand that this isn't your direct faults, but I need to be transparent here and voice my frustrations, especially as May 25th comes up in a week.

Really what I'm looking for is quite simple and I think the 99% case:

1. An HTTP example with no helper functions/GraphQL specifics (pretend I know absolutely nothing about GraphQL).
2. Good documentation (I honestly can't seem to find any) on how to get this special write key that allows you to do admin mutations. You should assume your customers won't want to try to login for each of these requests and that they'll make them on account deletion on their end.

**Comment by f2prateek** [comment]
hey @vhmth - I'll let @sperand-io respond to your request, but I wanted to quickly point out that the GDPR API is out of scope of this analytics-node library as mentioned previously. The team working on GDPR is not the same team as the team working on this library.

In order to make sure your questions get answered and don't get lost here in Github, I would highly recommend reaching out via our support https://segment.com/contact channel to make sure this request gets you connected you to the right people directly.

**Comment by vhmth** [comment]
@f2prateek thank you for being patient with me and calmly explaining things. I've gone ahead and messaged Segment directly. I suppose my frustration stems from the fact that this API overall feels like it's been slopped together (`gdpr.segment.com` isn't even resolving to an IP for me). Thanks for the calm response.
