### ISSUE TITLE
Use with Electron apps?

### ISSUE THREAD

**Issue by beriberikix** [segmentio/analytics-node#170]
https://github.com/electron/electron

Is this library officially supported to use with Electron or at least known to work? I noticed that [Nightmare](https://github.com/segmentio/nightmare), which is based on Electron, doesn't use it. If not, is the HTTP Tracking API recommended instead?

**Comment by beriberikix** [comment]
Gotcha. How would you recommend we implement tracking? There isn't a `page`.

**Comment by f2prateek** [comment]
yep - you can absolutely call screen (https://github.com/segmentio/analytics-node/blob/master/index.js#L124-L136). I don't have concrete tracking recommendations - but our support team http://segment.com/contact can help you out!
