### ISSUE TITLE
Promises instead of callback hell

### ISSUE THREAD

**Issue by victorbartel** [segmentio/analytics-node#171]
Hi,

I would like to know if you have any plan to “promisify” your node client. You seem to use `Axios.js` which is already promise compliant, so the shift must be seamless. Many thanks.

**Comment by f2prateek** [comment]
hey @victorbartel, currently there are no such immediate plans.

Are you referring to the public API? If so  - there are no callbacks here that you need to supply the library with, the  change would not be very helpful.

If you're referring to the internals, then yes, we may consider this in the future, but currently there are no such plans.

**Comment by villeodell** [comment]
@victorbartel you may be interested in https://github.com/segmentio/analytics-node/issues/93#issuecomment-419085126
