### ISSUE TITLE
Context in analytics.identify doesn't seem to work

### ISSUE THREAD

**Issue by aguynamedben** [segmentio/analytics-node#193]
I'm trying to pass context in analytics.identify...

```js
  analytics.identify({
    userId: id,
    traits: {
      email: email,
      accountsStats: getAccountsStats(accounts),
      providerIds: getAccountsProviderIds(accounts),
    },
    context: {
      app: {
        version: remote.app.getVersion(),
      },
    },
  });
```

The Segment debugger doesn't list context as being received (no app version)
![image](https://user-images.githubusercontent.com/107841/45854948-8bedc580-bd02-11e8-9a8a-7ade7756a3a2.png)

And I also don't see app version in Mixpanel.

The docs [here](https://segment.com/docs/sources/server/node/#identify) make it seem like analytics.identify does support context.

How can I pass app version at a single point in time? My app can be installed on multiple devices so it doesn't make sense to make it a trait (that would result in installs on multiple devices overwriting the version).

**Comment by f2prateek** [comment]
Did you check the `raw` tab?

**Comment by f2prateek** [comment]
I was able to send custom context fields using the code you provided - https://cloudup.com/cZtAW5pD4bY. As I mentioned, first check if this showed up in the debugger by using the "raw" tab. 

I suspect the issue may be something related to your setup. I recommend writing in to our support team - https://segment.com/contact.
