### ISSUE TITLE
analytics-node doesn't set set operating system context

### ISSUE THREAD

**Issue by aguynamedben** [segmentio/analytics-node#197]
I'm building an Electron app and want to track which OS and OS version each user is using. I went looking in MixPanel and Segment's debugger to see if that data is coming in, and it's not...
![image](https://user-images.githubusercontent.com/107841/49833058-4531c980-fd4d-11e8-9939-235d271f9627.png)

It [looks like](https://segment.com/docs/spec/track/#example) `context.userAgent` should be used to collect this data, and I'd expect analytics-node to detect and report the OS on its own. I'd then hope that Segment (or MixPanel) can break this value into more meaningful grouped values. I can obviously pass my own context values (or traits as a hack) to track this myself, but is there a recommended way to do this?

What I want is something like what Sentry does. I want os.version to be "Mac OS X 10.14.1" and I want that to flow through to MixPanel.

**Comment by f2prateek** [comment]
The server side libraries don't automatically collect this information, but you can send this yourself.

```
analytics.track({
  userId: '019mr8mf4r',
  event: 'Item Purchased',
  context: {
    userAgent: '...'
  }
});
```

**Comment by aguynamedben** [comment]
Based on [the context docs](https://segment.com/docs/spec/common/#context ) there is:
* `context.os.name`
* `context.os.version`

Is there any guidance (in Segment or MixPanel) on what these values should be? It's not very well documented what values should be passed. For example, on a Mac:
  * `os.platform()` returns `darwin` (not `macOS`)
  * `os.release()` returns `18.2.0` (not `10.14.1`)

Which version of these values should I pass? (Note: There are helper libraries [like this](https://github.com/sindresorhus/macos-release) to convert between Darwin version and macOS release.)

Does Segment (or MixPanel?) do anything "smart" with the `context.os.*` values? Should I just be using traits to pass my own "friendly" OS version? It seems that [these docs](https://segment.com/docs/spec/common/#context) say no custom context can be passed, so I guess traits is the only other option.

Side note: There's a broken link for "context" [the docs]() near "A dictionary of extra __context__ to attach to the call. Note: context differs from traits because it is not attributes of the user itself." (clicking context just goes to the top of the page).

**Comment by f2prateek** [comment]
>  It seems that these docs say no custom context can be passed, so I guess traits is the only other option.

You can pass spec'd context fields (e.g. context.os.name) but not "custom" fields (e.g. `context.foo.bar`). It'll show up in Segment, but it's likely not going to be sent to a destination as they wouldn't know what to do with it.

From what I know about Mixpanel - we send  `context.os.name` as `$os` to mixpanel and `context.os.version` as `$os_version` to Mixpanel. I also think Mixpanel parses info automatically from the userAgent, so if you just send the raw userAgent as shown in 
https://github.com/segmentio/analytics-node/issues/197#issuecomment-446380980, I _think_ it should show up in Mixpanel appropriately.

I would recommend reaching out to our support team, they'll be able to provide more details and best practices.

**Comment by aguynamedben** [comment]
Okay, thanks for the info, hopefully the docs can be improved a bit to explain nuances like this.

**Comment by f2prateek** [comment]
@aguynamedben I'll me follow up with you over email!
