### ISSUE TITLE
Add `enable` option to docs

### ISSUE THREAD

**Issue by lukehesluke** [segmentio/analytics-node#205]
Hi,

I've found the `enable` option (introduced here: https://github.com/segmentio/analytics-node/pull/158) to be useful in order to run automated tests that don't actually send events to Segment. However, had to do a bit of digging to find it.

Perhaps it should be in the docs? I'd be happy to do it myself if that helps 😊

**Comment by pbassut** [comment]
You mean in the docs here: https://segment.com/docs/connections/sources/catalog/libraries/server/node/
We add that ourselves. But thanks for offering help.

We'll add it soon. Thanks

**Comment by davidbielik** [comment]
Hi, I don't see this in [docs yet](https://segment.com/docs/connections/sources/catalog/libraries/server/node/#development). is this safe to rely on to disable segment in localhost, for example?

**Comment by pbassut** [comment]
@davidbielik On the `enable` property? Can't tell because at least the java library don't have such a thing. You can rely it on it on this version for sure. If we ever remove it we'll do a breaking change note. So don't worry.

**Comment by nd4p90x** [comment]
I have linked the PR that will close this request:  https://github.com/segmentio/segment-docs/pull/1933

Thank you,
