### ISSUE TITLE
EventCatagory and EventAction

### ISSUE THREAD

**Issue by codenamekt** [segmentio/analytics-node#206]
I need to add a category and an action to my payload for GTM and GA integration. While the standard library supports this, I am not seeing a way to do it with this library. Am I missing something? I can update the code to be a lighter weight wrapper as right now it seems there is some weird mappings happening like event in the analytics-node library track object gets mapped to the first argument in the regular library. These two track calls should really have the same syntax ie thin wrapper.

Example segment analytics call:
```
analytics.track('Event Account Logged Out', {
  action: 'Account Logged Out',
  category: 'Account',
  feature: 'Mission Control',
  location: '/',
  source: 'GUIV',
  userId: 'auth0|5c2e3bdfc5db266ab30b6dee'
});
```

What GA gets:
```
...
encoding         (&de)   UTF-8
VM54 analytics_debug.js:24 eventAction      (&ea)   Account Logged Out
VM54 analytics_debug.js:24 eventCategory    (&ec)   Account
VM54 analytics_debug.js:24 hitType          (&t)    event
VM54 analytics_debug.js:24 javaEnabled      (&je)   0
...
```

**Comment by codenamekt** [comment]
So, I created a payload: 
```
{  
  "userId":"auth0",
  "action":"Did Things",
  "source":"GUIV",
  "event":"Did Things",
  "category":"Organization",
  "properties":{  
    "auth0ClientName":"Batman",
    "auth0ClientID":"123"
  },
  "context":{  
    "library":{  
      "name":"analytics-node",
      "version":"3.3.0"
    },
    "userAgent":"Batman",
    "ip":"111.111.111.111"
  },
  "type":"track",
  "_metadata":{  
    "nodeVersion":"10.15.3"
  },
  "timestamp":"2019-06-03T19:09:10.907Z",
  "messageId":"node-439af91571770c9d74680be799cfe702-204da029-cd9e-40c2-ac1e-3bd2544066b1"
}
```
I verified it is being sent to segment, through this library by adding some `console.log` messages in the `flush` method around ~L254.

What segment sees in the debugger is:
```
analytics.track({
  userId: 'auth0',
  event: 'Did Things',
  properties: {
    auth0ClientID: '123',
    auth0ClientName: 'Batman'
  }
});
```

You can see segment isn't getting a decent amount of the properties. At this point though, I've run out of options on debugging or solving this myself I believe because I'm thinking the issue lies within the segment api and what it does with the message.

I'm more than happy to provide additional context and sample code to recreate the problem if necessary.

**Comment by f2prateek** [comment]
@codenamekt I believe you're looking in the "pretty" view in the debugger. if you see the raw payload, it should show more fields. I would recommend reaching out to our support team (https://segment.com/contact/) to help you understand the Google Analytics integration mappings.

**Comment by codenamekt** [comment]
I was correct in my assumption. It looks like the API allows for event but not category. I believe the API when sent additional properties is just dropping them off the payload:

https://segment.com/docs/sources/server/http/#track

The client side segment library allows these values and we have created all of our events with these properties. I'd like to see the api start supporting additional items in the payload at least these two if not more.

Example event coming from our client side segment calls:

```
analytics.track('Credit Card Added', {
    action: 'Credit Card Added',
    category: 'Billing',
    source: 'GUIV',
    userId: 'auth0|5cf547457886670e6127b334'
  });
```

**Comment by codenamekt** [comment]
Wow, thanks for the response. It's odd but when sending events via the client side library I see these `key:values` in the pretty view but not when sending these events via the analytics-node library. I made the assumption I would be able to see it in the pretty view regardless of the method I was using which lead me down this rabbit hole.
