### ISSUE TITLE
Upgrade axios to >=0.19.0 to fix vulnerability

### ISSUE THREAD

**Issue by letsgolesco** [segmentio/analytics-node#209]
See NPM advisory: https://www.npmjs.com/advisories/880

Their changelog doesn't flag any breaking changes since 0.17.1 so this should be a safe upgrade

**Comment by shawn-rival** [comment]
I made a PR for this 5 days ago but not sure who to reach out to to get this merged: https://github.com/segmentio/analytics-node/pull/208

**Comment by f2prateek** [comment]
Closed by #211

**Comment by nicogon** [comment]
all 0.18.x versions are vulnerable, fixed on 0.19
axios/axios#1098, please merge 
https://github.com/segmentio/analytics-node/pull/218

**Comment by shawn-rival** [comment]
The fix was backported to 0.18.1: https://github.com/axios/axios/releases/tag/v0.18.1
