### ISSUE TITLE
axios-retry package is problematic

### ISSUE THREAD

**Issue by broom9** [segmentio/analytics-node#223]
It's currently in the dependency but it hangs on network errors. Please consider to use an alternative solution.

**Comment by dhakalsuresh** [comment]
it's takes me forever to figure out that this package hangs on network errors and consumes all CPU

**Comment by g-guirado** [comment]
axios-retry does not work with axios 0.19.0 (https://github.com/softonic/axios-retry/issues/59, also mentioned on https://github.com/softonic/axios-retry/blob/master/README.md).

Why does an analytics package use axios-retry? IMHO analytics should be best effort and dropped on error, no need to retry (or at least retry shouldn't be the default behavior)

**Comment by Floriferous** [comment]
Analytics should definitely not be dropped! We rely on our analytics as a high-trust datasource, for some of our low-volume events, we don't want a single one of them to be dropped.

**Comment by pooyaj** [comment]
Closing since there has been few updates to axios since then. Please feel free to re-open if still an issue
