### ISSUE TITLE
Support Http Proxy

### ISSUE THREAD

**Issue by chanind** [segmentio/analytics-node#224]
Axios works with http proxies, but this library doesn't expose a way to configure the http proxy setting, at least as far as I can tell. I can make this work by doing the following:

```js
// hackily import axios out of the analytics-node module
import analyticsAxios from 'analytics-node/node_modules/axios';
analyticsAxios.defaults.proxy = {
  host: 'x.x.x.x',
  port: 1234,
};
```
and in package.json:
```
  "resolutions": {
    "analytics-node/axios": "^0.19.0"
  }
```

Axios before 0.19.0 has a [bug with https proxies](https://github.com/axios/axios/pull/959), so I needed to upgrade the version of axios used by `analytics-node` to 0.19.0, since the currently published version is not on 0.19.0 yet.

Is there a less hacky way to accomplish this?

**Comment by aliyeysides-vg** [comment]
@chanind just ran into the same issue. It would be nice if there was an option to pass in a custom httpAgent when instantiating `Analytics` or at the very least pass in the proxy config options like you mentioned. I only briefly looked at the source code but this shouldn't be too hard to implement? If the maintainers are open to it, I can make a PR for this.

**Comment by pbassut** [comment]
[This](https://github.com/segmentio/analytics-node/pull/240) should solve that. It would also make it highly configurable since we'll have access to the axios instance.

**Comment by igorantun** [comment]
@pbassut Although this PR allows passing an axios instance/options to `this.axiosInstance`, it doesn't seem to be used later on. (I couldn't find any occurence of `this.axiosInstance` outside the constructor)

Apparently it's `this.axiosClient` that is actually used, and it receives neither the instance or the options passed to the constructor (https://github.com/segmentio/analytics-node/blob/e39cf68c4add105873146f055571404aed799d02/index.js#L56)

Am I missing something? Thanks for looking into this :)

**Comment by pbassut** [comment]
You're spot on. Likely a merging error. We'll fix it ASAP

**Comment by igorantun** [comment]
Thanks @pbassut :)

**Comment by pbassut** [comment]
Closed by https://github.com/segmentio/analytics-node/pull/270
