### ISSUE TITLE
Data parameter does not return any data when calling .track method

### ISSUE THREAD

**Issue by albertmourato** [segmentio/analytics-node#230]
When calling `.track` method, it may receive a callback function that has as parameters `(error, data)`. `error` is coming `undefined` which is good, since my code was executed successfully, however, `data` always comes `undefined` which is not good at all.

**Comment by yuriedmundo** [comment]
I have the same problem

**Comment by Chathula** [comment]
same issue here. I checked the code. actually it doesn't return anything as I see :(

**Comment by pbassut** [comment]
We're looking into it. PR looks good. Will have updates soon
