### ISSUE TITLE
Not working with mongoose?

### ISSUE THREAD

**Issue by mebibou** [segmentio/analytics-node#232]
I have the strangest thing happening:
- when I write this code, the events are sent over to segment and I can see them in the debugger
```javascript
const Analytics = require('analytics-node');
const analytics = new Analytics('WRITE_KEY', { flushAt: 1 });

analytics.track({
  anonymousId: 'anonymousId',
  event: `Clicked CTA ${new Date().toJSON()}`,
  properties: {
    location: 'header',
    type: 'button'
  }
});
```
- now if after the same code I do a mongoose connection, the events are not being sent anymore

Anybody knows why? I tried using different version of the library (2 and 3) but same problem

**Comment by pbassut** [comment]
Sorry being so late on this but, mind sharing how you do the the mongoose connection as well?

**Comment by pbassut** [comment]
I don't see why this wouldn't work with mongoose. Maybe you're [stumbling upon this](https://github.com/segmentio/analytics-node/issues/223) as well(i.e. hanging on network errors?)
