### ISSUE TITLE
Infinite loop due to axios 0.19.x and axios-retry

### ISSUE THREAD

**Issue by Floriferous** [segmentio/analytics-node#239]
Issues have been opened in `axios` and `axios-retry`, as a combination of `axios` 0.19.x and `axios-retry` 3.1.x are causing this package to end up in an infinite loop.

Relevant issues:
* https://github.com/axios/axios/issues/2203
* https://github.com/softonic/axios-retry/issues/110

Some people are reporting that the issue is gone for them in `0.19.2`, but not on our end.

**Comment by pbassut** [comment]
Fixed at https://github.com/segmentio/analytics-node/pull/255
