### ISSUE TITLE
Track method is too strict with types

### ISSUE THREAD

**Issue by karbica** [segmentio/analytics-node#242]
Hello.

The `@types/analytics-node` package provides types that are too strict preventing the application from meeting the requirements of the schema defined on Segment.

https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/analytics-node

The HTTP API does not force required properties except for `event`. The types described in the repository above force requirements that prevent the client from being able to validate against the schema defined in the Segment web application.

**Comment by pooyaj** [comment]
@karbica that is a community maintained package. feel free to open a PR against DefinitelyTyped
