### ISSUE TITLE
32kb warning out of date

### ISSUE THREAD

**Issue by thejuan** [segmentio/analytics-node#244]
`console.log('Your message must be < 32kb. This is currently surfaced as a warning to allow clients to update. Versions released after August 1, 2018 will throw an error instead. Please update your code before then.', message)`

Looks like segment is dropping the message, but no error is thrown.

**Comment by pbassut** [comment]
You're right. That's a two-liner. If you wanna take a look at that we'll gladly accept PRs. 
Thanks!
