### ISSUE TITLE
Support for serverless environments?

### ISSUE THREAD

**Issue by Blatty** [segmentio/analytics-node#245]
Hello,

First of all, thank you to the segment team for providing this library.

I'm currently trying to implement analytics-node in my serverless app (GraphQL + nowsh, now known as [vercel](https://vercel.com/).

I tried using a shorter `flushInterval` like mentioned in this comment: https://github.com/segmentio/analytics-node/issues/121#issuecomment-382463201 but it looks like `context.callbackWaitsForEmptyEventLoop` needs to be set to `true`, however Vercel, under the hood, use `context.callbackWaitsForEmptyEventLoop = false` by [default](https://github.com/vercel/now-builders/pull/505).

Is there any recommended  guide to use this library in a serverless environment / is it supported?

**Comment by sbassin** [comment]
I'm having similar issues in a Lambda even with `context.callbackWaitsForEmptyEventLoop` set to true. Did you ever find a solution to this? Did you end up integrating with the Segment HTTP services?

**Comment by mccraveiro** [comment]
I don't think that's the best solution but you could call `.flush()` at the end of your function handler.

**Comment by Blatty** [comment]
`.flush()` won't work at is will just process the queue synchronously.

@sbassin We forked it to use the same api, removed the queue system and made async calls with `undici` instead of `axios`.

**Comment by sbassin** [comment]
I ended up posting to the Segment trace HTTP endpoint.

**Comment by ItsWendell** [comment]
I'm glad I ran into this, @Blatty do you have your fork available? I'm also starting to implement it in lamdba / Vercel.

**Comment by davidparys** [comment]
I'm having a similar issue with NextJs and vercel. It doesn't seem to flush it no matter if I call `analytics.flush() ` or setting a `flushAt: 1`  as mentionned in the [Segment Node Docs](https://segment.com/docs/connections/sources/catalog/libraries/server/node/#development).

**Comment by pbassut** [comment]
Did anyone trace the root cause of the issue? Does lambdas finish and kill all threads(unusual) before the queue is actually flushed?

**Comment by tclass** [comment]
have the same problem, even when I call flush(), as it's non-blocking it can happen that the function ends before flush() finished, can't we have a blocking flush() function. It might not be useful in client facing apps, but on the service-side it's totally fine

**Comment by sayerrrr** [comment]
Any status on this from the Segment team? this is pretty crucial for us and would love to hear a timeline on when this package will be available for serverless enviroments.. 

@Segment, any updates??

**Comment by pbassut** [comment]
Hey everyone. We're working on this as of now should have a solution ASAP.

I'm wondering if just returning `.post` here https://github.com/segmentio/analytics-node/blob/master/index.js#L278 if that wouldn't allow us to await(this making it sync/blocking).

some inputs here would be nice. Maybe I'm not in the loop here

**Comment by milo-** [comment]
@pbassut are you able to release a new version on npm with your flush promise fix? I've been testing in our environment (Google cloud functions) and it seems to be working well 👍

**Comment by pbassut** [comment]
Yeah, sure.
That's good cause I've been testing on AWS Lambda and it seems to be working well too.
But I was looking to have confirmation from someone else using lambda. 

But we'll make a release anyway.

**Comment by jkarsrud** [comment]
> But I was looking to have confirmation from someone else using lambda.
@pbassut If you are still looking at confirmation, I just tested this on my end and the fix seems to be working just fine :+1:

**Comment by mikeblanton** [comment]
@pbassut can you confirm what specifically needs to be done to take advantage of this? We're working with one of your SA's and he pointed us to this fix to help with some visibility problems we're having in Lambda. We're triggering events off of Lambda's that process DynamoDB streams. I've got our flushAt set to 1. I'm also explicitly calling via an await.  I can see in Lumigo that the call to segment is going out. I can see in my logs that the flush call completes, but I don't see confirmation in the logs (or in lumigo) that the calls actually finish.

For example, I've got these 2 helper functions:

```
module.exports.flush = async (logger) => {
  await analytics.flush(function (err, batch) {
    if (logger) {
      if (err) {
        logger.error(err);
        return;
      }
      logger.debug('Segment cache flushed', {batch});
    }
  });
}

module.exports.track = async (payload, logger) => {
  analytics.track(payload, function (err, batch) {
    if (logger) {
      if (err) {
        logger.error(err, payload);
        return;
      }
      logger.debug('Batch flushed', {batch, payload});
    }
  });
  if (logger) {
    logger.debug('Segment track call sent', {payload});
  }
}
```

In my logs, I see...
- `Segment track call sent`
- `Segment cache flushed`

But I never see `Batch flushed`.

**Comment by andreaminieri** [comment]
@mikeblanton I'm having exactly the same issue in a Vercel serverless function: did you find a solution for this?

**Comment by pbassut** [comment]
@mikeblanton Sorry I missed this. Can you create an issue for that so we can track more closely?
I'm assuming you did upgrade to the latest library version

**Comment by mikeblanton** [comment]
@andreaminieri see the comment in #305 for my workaround. Not sure if it will work for you or not.
