### ISSUE TITLE
[Amplitude] Customize platform field

### ISSUE THREAD

**Issue by AMoreaux** [segmentio/analytics-node#249]
Hello,

Is there a solution to customize the value of the platform field with amplitude.
From analytics.js it's `Web` and from analytics-node it's `analytics-node`.
For example, I would like to use API or APP instead of the name of the library used.

**Comment by pbassut** [comment]
Hello!
For the time being, there isn't. But when [this PR](https://github.com/segmentio/analytics-node/pull/240) comes through you will be able to modify the request however you like with Axios' interceptors! :D
