### ISSUE TITLE
`npm install analytics-node@latest` installs beta instead of stable version

### ISSUE THREAD

**Issue by stephledev** [segmentio/analytics-node#256]
Version `3.4.0-beta.3` of `analytics-node` is currently tagged as the `latest` version in the package registry of npm https://www.npmjs.com/package/analytics-node. This means that `npm -i` will default to installing a beta version instead of a stable one. While this is not a wrong behaviour per se, it's for sure unexpected compared to most other libraries.

**Comment by pooyaj** [comment]
Fixed the issue. 3.5.0 is the latest now!
