### ISSUE TITLE
Would be nice if there was analytics.debug()

### ISSUE THREAD

**Issue by fourcolors** [segmentio/analytics-node#286]
It would be nice if there was `.debug()` like on the AnalyticsJS package that would log out events for you as they happened.

**Comment by pbassut** [comment]
Hello!
Did you check out the [source debugger](https://segment.com/docs/connections/sources/debugger/) yet?
Wouldn't that address your use case?

**Comment by fourcolors** [comment]
Oh I haven't seen that.  Where can I access that debugger tool? I think that would handle my case actually.

**Comment by pbassut** [comment]
You need a segment account and then you go to your Sources > [Source Name] > Debugger Tab.
