### ISSUE TITLE
Console Error "axiosRetry is not a function"

### ISSUE THREAD

**Issue by soldmtrieu** [segmentio/analytics-node#304]
Hi there,

It looks like a recent update in one of your npm dependencies throws the following error "axiosRetry is not a function".

Looks like version 3.2.2 or 3.2.1 may be the culprit. Any way to lock this dependency in at version 3.2.0?

More details here ~ [https://github.com/softonic/axios-retry/issues/181](https://github.com/softonic/axios-retry/issues/181)

**Comment by ran2207** [comment]
Hi Team,

Yes,  even we have been facing this problem and as mentioned above it seems to be due to the axios-version version 3.2.2 most likely.

**Comment by sukybal1010** [comment]
Hi team

this is preventing our deployments as they are failing.

**Comment by pooyaj** [comment]
Hey folks, updated `axios-retry` to the latest which should solve the issue. Let me know if still seeing the errors.
