### ISSUE TITLE
`enque` callback called twice when flush is triggered

### ISSUE THREAD

**Issue by yo1dog** [segmentio/analytics-node#308]
The callback passed to `enque` can be called twice if a flush is triggered. The callback is passed both to the queued message and to `flush`:

https://github.com/segmentio/analytics-node/blob/70f24fe031f616a9c95f3d8ae345174f07df98cb/index.js#L210-L223

When `flush`'s `done` function is called, the callback is called twice: Once from the `callbacks` array (as it was added to the array from the queued message) and again when `callback` is called (as it was passed to `flush` as the `callback` argument).

https://github.com/segmentio/analytics-node/blob/70f24fe031f616a9c95f3d8ae345174f07df98cb/index.js#L265-L268

The fix is to not pass `enque`'s callback to `flush`.

In general, a callback should never have more than 1 handler.

**Comment by felipe-najson-ntf** [comment]
Hello @yo1dog, this issue will be solved with pr #299 which I requested to merge ASAP.
Thanks for your contributution again!

Segment team
