### ISSUE TITLE
Node-js events landing into Google Analytics bowser data ?

### ISSUE THREAD

**Issue by GilesLeRockeur** [segmentio/analytics-node#312]
Hey folks, isn't it weird that Segment.io appears in this table on _Google Analytics_ > _Audience_ > _Technology_ > _Browser & OS_ ? (screenshot below)

I'm suddenly worried that I've been analysing duplicated traffic data.

In Segment I've only 3 items that are "ON" in my Node-JS > GA connection : 
- Track categorised page
- Track named page
- Set Custom Dimensions & Metrics to the Page

I don't understand what this data is. Could you help me understand please ?

Thanks a lot

Happy Monday to everyone !

![Screenshot 2021-11-29 at 10 59 07](https://user-images.githubusercontent.com/66418609/143856190-e8ed5ecd-1436-47f7-a69c-5ead3b59884a.png)

**Comment by nd4p90x** [comment]
@GilesLeRockeur We are looking into this and will get back with you shortly, thank you.

**Comment by pooyaj** [comment]
@GilesLeRockeur Having the `Segment.io` in the list makes sense, as our cloud mode integration sets the User-Agent to `'Segment.io/1.0'` ... I'm not sure where the rest of User-agents are coming from tho.
