### ISSUE TITLE
analytics-node might cause an unhandledRejection

### ISSUE THREAD

**Issue by yigaldviri** [segmentio/analytics-node#320]
Hi there, 

Im trying to use this package to report events to Segment and as a consumer I'm trying to protect my server from errors. My code looks like this:

```
track = promisify(analytics.track.bind(analytics));

async report (userId: string, eventType: SegmentEvent, properties) {
    try {
      await track({
        userId,
        event: eventType,
        properties: addLinkToProperties(eventType, properties),
      });
    }
    catch (e) {
      log.warn('Couldn\'t report to segment about event', { eventType, properties, e });
    }
  }
```

I had a look at the package's code and I think that In some cases the package can cause an unhandledRejection error. For examplee, in case of a downtime on Segment servers.

I simulated it by changing the code and throwing an error inside the `then` clause of the `flush` function:
![image](https://user-images.githubusercontent.com/13430395/150319930-e3c849cf-f40c-403d-9a25-13701f88188b.png)

Tested it an indeed I got `[ERROR] - unhandledRejection: Error: test an error`

This kind of error might result in a server crush and using `try/catch` wont help either so am I missing here something? Is there a way to avoid that error? Or maybe my case can't really happen in reality?

**Comment by nd4p90x** [comment]
Please re-open if more discussion is needed.  Thank you

**Comment by GarrettCox** [comment]
What is the solution here? Apps can have intermittent network disruptions, and a fatal unhandled promise rejection is a poor user experience.

**Comment by supermacro** [comment]
> Please re-open if more discussion is needed. Thank you

As requested by @nd4p90x ... looks like more discussion is needed. Could we re-open?

**Comment by edsonjab** [comment]
Hi @GCAndrew , @supermacro , @yigaldviri ,  I found a solution for this issue. You can handle the error with the next code:

![image](https://user-images.githubusercontent.com/22898327/171959890-013034e2-2fb4-4402-bd9a-0c38e03e6a63.png)

The node process global has [an unhandledRejection event](https://nodejs.org/api/process.html#process_event_unhandledrejection) for unhandled promise rejection.

**Comment by tam-carre** [comment]
@edsonjab it works but as said in #326, 

> Listening for uncaught exception events isn’t an ideal error handling pattern.

It is very user-unfriendly to require that the library's exceptions be handled inside the `unhandledRejection` handler.

**Comment by rdsedmundo** [comment]
Just hit this and it crashed subsequent unrelated Lambda requests, this is definitely a poor experience and using `.on('unhandledRejection')` is not an acceptable solution, just return a regular `Promise` in the `track` event instead of skipping it.

**Comment by supermacro** [comment]
Is this repo accepting PRs to address this issue? Either myself or a colleague are happy to submit a PR

**Comment by edsonjab** [comment]
Hi @supermacro, yes please, you can make a PR and we will check your solution.

**Comment by supermacro** [comment]
Ok we've added this as an item on our backlog, can't promise an ETA but good to know that we can submit a PR when we get some time!

**Comment by yigaldviri** [comment]
When are you planning on publishing the updated package to npm?

**Comment by nd4p90x** [comment]
Release 6.1.0 will resolve this issue, thank you.
