### ISSUE TITLE
Chrome extension background service worker + analytics-node = fail

### ISSUE THREAD

**Issue by rony-arnac** [segmentio/analytics-node#335]
Hey!

there's an issue with using axios in the background service of chrome extensions with manifest v3.
the adapter isn't configured and axios requests fail.

> adapter is not a function

is there a workaround to fix this issue?

I tried defining `axios.defaults.adapter` but it didn't take -- adapter is still undefined.

**Comment by rony-arnac** [comment]
I have a workaround:

```
analyticsProvider = new AnalyticsProvider(apiKey);
...
...
(analyticsProvider as any).axiosInstance.defaults.adapter = fetchAdapter;
```

**Comment by edsonjab** [comment]
Hi @rony-arnac, what version of analytics-node are you using?
