### ISSUE TITLE
Callback is called for each tracked event with the entire batch data 

### ISSUE THREAD

**Issue by godspeedelbow** [segmentio/analytics-node#34]
In `Analytics.prototype.flush` on line 161, the entire batch data is passed to the callback:

```
fns.forEach(function(fn){ fn(err, data); });
```

When you implement `node-analytics` you don't expect your callback to be called once for each tracked event **with the entire batch data**. Because that resulted in many hundreds of kb's of log statements for each flush, we now ignore the data passed back:

```
analytics.track(props, function (err) //removed function (err, data) {
  if(err){
    return log.error(err);
  }
  console.log('segment.io: tracked: %j', props); //log props instead of data
});
```

I would advice to change line 161 to:

```
fns.forEach(function(fn){ fn(err); }); //no data passed back
```

**Comment by hankim813** [comment]
@ndhoule is this something we should still consider adding? https://github.com/segmentio/analytics-node/blob/master/analytics-node.js#L155 is the updated line number in regards to this

**Comment by vadimdemedes** [comment]
Agree, it doesn't make sense to pass the data from all calls to the callbacks.
