### ISSUE TITLE
Npm version update for Axios Version update

### ISSUE THREAD

**Issue by esker** [segmentio/analytics-node#343]
Hello, I've had to update axios in my project to work with webpack 5. I'm also using this project in my stack as well. I can see that about a month ago this project has been updated with the latest axios as well, but the npm version (which my CI uses) is out of date. Are there any plans to update the npm package in the future? I'm currently using a forked version but I'd rather not miss out on any other crucial updates in doing so.

**Comment by nd4p90x** [comment]
@esker A new version has been released, npm 6.1.0.  Thank you 
https://www.npmjs.com/package/analytics-node
