### ISSUE TITLE
Support for other backend JS runtimes (Web Workers, Deno)

### ISSUE THREAD

**Issue by davidhousedev** [segmentio/analytics-node#345]
We are hoping to dispatch backend events from Shopify's Hydrogen framework, which is deployed in Web Workers. Do you all have any plans to add a source that's compatible with JS web workers? This could also be applicable to other edge-enabled frameworks like NextJS and Remix.

**Comment by pooyaj** [comment]
Hi @davidhousedev! We are planning to add support for worker environments in [analytics.js](https://github.com/segmentio/analytics-next) ... stay tuned as we should release this summer.

**Comment by pooyaj** [comment]
cc @chrisradek @silesky

**Comment by huksley** [comment]
Now it is Autumn already... Do we have a more lightweight version for serverless, node and web workers?

I especially would appreciate fewer dependencies (ideally ZERO) for the node version.

**Comment by silesky** [comment]
https://github.com/segmentio/analytics-next/tree/master/packages/node supports lambda.

I haven't tested yet, but it _should_ also support CF workers and most likely web workers (no device mode destinations, obviously). I'd be interested to get some feedback here.

**Comment by silesky** [comment]
[@segment/analytics-node](https://github.com/segmentio/analytics-next/tree/master/packages/node) now supports worker runtimes.
