### ISSUE TITLE
Cross-Domain Misconfiguration

### ISSUE THREAD

**Issue by quipo** [segmentio/analytics-node#359]
When using this library, and pen-testing the application with [OWASP ZAP](https://www.zaproxy.org/), we get a Medium severity alert:

Medium | Cross-Domain Misconfiguration
-- | --
Description | Web browser data loading may be possible, due to a Cross Origin Resource Sharing (CORS) misconfiguration on the web server
URL: | https://cdn.segment.com/analytics.js/v1/XXXXXXXXXXXXXXX/analytics.min.js
Evidence: | Access-Control-Allow-Origin: *
Solution | Ensure that sensitive data is not available in an unauthenticated manner (using IP address white-listing, for instance).Configure the "Access-Control-Allow-Origin" HTTP header to a more restrictive set of domains, or remove all CORS headers entirely, to allow the web browser to enforce the Same Origin Policy (SOP) in a more restrictive manner.
Reference | https://vulncat.fortify.com/en/detail?id=desc.config.dotnet.html5_overly_permissive_cors_policy
Tags | OWASP_2021_A01 OWASP_2017_A05
CWE Id | 264
WASC Id | 14

How do we configure the script inclusion so it doesn't raise this warning?

**Comment by quipo** [comment]
Similarly, getting `Strict-Transport-Security Header Not Set` (Low) alert.

HTTP Strict Transport Security (HSTS) is a web security policy mechanism whereby a web server declares that complying user agents (such as a web browser) are to interact with it using only secure HTTPS connections (i.e. HTTP layered over TLS/SSL). HSTS is an IETF standards track protocol and is specified in RFC 6797.

**Comment by edsonjab** [comment]
Hi @quipo thank you for your report, we start looking into this.

**Comment by quipo** [comment]
`X-Content-Type-Options` Header Missing

The Anti-MIME-Sniffing header X-Content-Type-Options was not set to 'nosniff'. This allows older versions of Internet Explorer and Chrome to perform MIME-sniffing on the response body, potentially causing the response body to be interpreted and displayed as a content type other than the declared content type.

**Comment by silesky** [comment]
Hey! This is a deliberate server side configuration, as the analytics CDN is meant to allowed to be queried in any environment. It was deliberate -- this seems like a false alarm.

 Also, this browser specific feature, and has no relevance to the server / node at all.

**Comment by quipo** [comment]
Thanks @silesky.  That makes sense. What about the `Strict-Transport-Security` and `X-Content-Type-Options` headers though?

**Comment by silesky** [comment]
HSTS - not relevant, we do allow http

nosniff - I'm not responsible for security, but this doesn't seem  relevant to static .js files where mine type sniffing isn't a thing.
