### ISSUE TITLE
Re-use same analytics instance across Express routes?

### ISSUE THREAD

**Issue by kevinSuttle** [segmentio/analytics-node#43]
Is there a way `app.use()` with this module?

**Comment by travisjeffery** [comment]
Hey Kevin, thanks for the question. You could create a create an instance of analytics, and add a middleware to the front that tacks the instance on to the req so it'll be shared/passed through the other middlewares. 

e.g.

```
var analytics = new Analytics('...');

app.use(function(req, res, next){
  req.analytics = analytics;
  next();
});
```

Thanks and let me know if you have any further questions!

**Comment by kevinSuttle** [comment]
Great idea. Thanks!

**Comment by kevinSuttle** [comment]
Actually, this returns `undefined` when accessed through middleware.


**app.js**
```
app.use(function(req, res, next) {
	req.analytics = analytics;
	next();
});
```

**middleware.js**
```javascript 
req.analytics.track({
	userId: req.user.id,
	event: 'Clicked Sign up'
});
```
```bash
TypeError: Cannot read property 'track' of undefined
```

Do I need to `require(app)` in each middleware?

**Comment by GarthDB** [comment]
@kevinSuttle if you use the example code

```js
var express = require('express');
var xa = require('express-analytics');

var app = express();
...
app.use(xa());
...
```

Does that not work for all requests?

**Comment by kevinSuttle** [comment]
It's odd. It works for one middleware, a route filter, but not inside another route's Router instance.

**Comment by GarthDB** [comment]
Without seeing the whole app I'm not sure. Just stabbing in the dark here: what about the order? Middleware is always invoked in the order added.

**Comment by kevinSuttle** [comment]
I made sure to put it last in app.js.

Maybe the fact that I'm using it in a Passport authorize() callback? 
```javascript
router.get('/callback',
	passport.authorize('github'),
		function(req, res) {
			if (req.account) {
				req.user.githubAccount = req.app.locals.user.githubAccount = req.account;
				console.log(req.user); // all user data
				console.log(req.analytics); // undefined   
                                console.log(req.app.locals.analytics); // undefined
                                console.log(req.locals.analytics); // undefined
				req.analytics.track({
					userId: req.user.id,
					event: 'Authorized GitHub'
				});
				res.redirect('/profile');
			}
			else {
				res.redirect('/login');
			}
		}
);
```

**Comment by GarthDB** [comment]
Can you take it out and test it to see if there's a conflict somewhere?

**Comment by kevinSuttle** [comment]
Actually, that was a false positive in working in the route filtering middleware. It was the client-side snippet. But it was being called twice, which made it look like it was both Node and the client-side snippet. Anyway.

`req.analytics` is actually never being set.

**Comment by kevinSuttle** [comment]
@travisjeffery Any ideas?

**Comment by travisjeffery** [comment]
you don't want to put it last, you want to put it first. middleware is executed in the order that they're added.

**Comment by travisjeffery** [comment]
just double checked that this works, so it's gotta be something going on in your app.

server.js:

```js
var express = require('express');
var Analytics = require('analytics-node');
var analytics = new Analytics('write key');
var app = express();

app.use(function(req, res, next){
  req.analytics = analytics;
  next();
});

app.get('/', function(req, res){
  console.log('analytics: ', req.analytics);
  res.send('Hello, world!');
});

var server = app.listen(3000, function(){
  console.log('App listening on :3000');
});
```

```
🍕  node server.js&
[2] 15146

~
App listening on :3000

$ curl localhost:3000

analytics:  { queue: [],
  writeKey: 'write key',
  host: 'https://api.segment.io',
  flushAt: 20,
  flushAfter: 10000,
  proxy: null }

Hello, world!
```

**Comment by kevinSuttle** [comment]
@travisjeffery @GarthDB I got it. Something was off with the order, as it almost always is with Express middleware. I moved it _after_ the Express scaffolding (view engine, static directory, etc.),  but _before_ the routes and session info. 

Thanks so much for your help.
