### ISSUE TITLE
conflict with superagent depend

### ISSUE THREAD

**Issue by rgnevashev** [segmentio/analytics-node#44]
since with version 1.1.1 npm install give error:
npm ERR! peerinvalid The package superagent does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer superagent-proxy@0.3.2 wants superagent@>= 0.15.4 && < 2
npm ERR! peerinvalid Peer superagent-retry@0.4.0 wants superagent@~0.19.0

Thanks for package!

**Comment by wallslide** [comment]
I tried to use this package as part of this package: https://github.com/percolatestudio/meteor-segment.io

I got the exact same error as @rgnevashev when trying to deploy my project to Modulus.io

**Comment by hankim813** [comment]
Hey guys, could you guys let me know if this is still an issue? Let me know and I'll reopen!
