### ISSUE TITLE
Cannot npm install analytics-node

### ISSUE THREAD

**Issue by foster** [segmentio/analytics-node#45]
analytics-node depends on a thing who depends on a guy who deleted his git branch.

    ├─┬ analytics-node@1.2.2
    │ │ The hassle-free way to integrate analytics into any node application.
    │ │ git://github.com/segmentio/analytics-node.git
    │ │ https://github.com/segmentio/analytics-node
    │ └─┬ superagent-proxy@0.3.2
    │   │ `Request#proxy(uri)` superagent extension
    │   │ git://github.com/TooTallNate/superagent-proxy.git
    │   │ https://github.com/TooTallNate/superagent-proxy#readme
    │   └─┬ proxy-agent@1.1.0
    │     │ Maps proxy protocols to `http.Agent` implementations
    │     │ git://github.com/TooTallNate/node-proxy-agent.git
    │     │ https://github.com/TooTallNate/node-proxy-agent
    │     └─┬ pac-proxy-agent@0.2.0
    │       │ A PAC file proxy `http.Agent` implementation for HTTP
    │       │ git://github.com/TooTallNate/node-pac-proxy-agent.git
    │       │ https://github.com/TooTallNate/node-pac-proxy-agent
    │       └─┬ pac-resolver@1.2.6
    │         │ Generates an asynchronous resolver function from a PAC file
    │         │ git://github.com/TooTallNate/node-pac-resolver.git
    │         │ https://github.com/TooTallNate/node-pac-resolver
    │         └─┬ degenerator@1.0.1
    │           │ Turns sync functions into async generator functions
    │           │ git://github.com/TooTallNate/node-degenerator.git
    │           │ https://github.com/TooTallNate/node-degenerator
    │           ├─┬ escodegen@1.3.3
    │           │ │ ECMAScript code generator
    │           │ │ git+ssh://git@github.com/Constellation/escodegen.git
    │           │ │ http://github.com/Constellation/escodegen
    │           │ └── esprima@1.1.1 
    │           │     ECMAScript parsing infrastructure for multipurpose analysis
    │           │     git+ssh://git@github.com/ariya/esprima.git
    │           │     http://esprima.org
    │           └── esprima@1.1.0-dev-harmony  (git+https://github.com/ariya/esprima.git#a41a40b49046747b3af57341cda048bbd3d9df79)
    │               ECMAScript parsing infrastructure for multipurpose analysis
    │               git+ssh://git@github.com/ariya/esprima.git
    │               http://esprima.org
    │               git+https://github.com/ariya/esprima.git#harmony

Downstream:  TooTallNate/node-degenerator#7

**Comment by cariseterravion** [comment]
Experiencing this problem as well.

**Comment by zacharyolson** [comment]
Same here :(

**Comment by sent-hil** [comment]
ditto

**Comment by cariseterravion** [comment]
Seems to be working now. TooTallNate fixed the issue.

**Comment by gjohnson** [comment]
They just fixed the issue with a downstream dependency, can you try re-installing?

**Comment by foster** [comment]
Yep, looks fixed downstream. Appreciate the quick response! Feel free to close.
