### ISSUE TITLE
This module has side effect of leaking window._ (set to lodash)

### ISSUE THREAD

**Issue by cymen** [segmentio/analytics-node#48]
This module has a side effect of leaking to `window._` with it set to lodash.

**Comment by cymen** [comment]
Also I get this is intended for node server side but where is the Segment IO node module for client-side development?

**Comment by hankim813** [comment]
The core logic for client side would be https://github.com/segmentio/analytics.js-core but the open sourced version is indeed at https://github.com/segmentio/analytics.js

**Comment by f2prateek** [comment]
Reopening since this is still an issue.

**Comment by vadimdemedes** [comment]
Will be fixed when https://github.com/segmentio/analytics-node/pull/110 is merged, since it removes lodash altogether.

**Comment by vadimdemedes** [comment]
New release is out - https://github.com/segmentio/analytics-node/releases/tag/v3.0.0, which doesn't use lodash anymore.
