### ISSUE TITLE
mime 1.2.2 suddenly missing

### ISSUE THREAD

**Issue by eshao** [segmentio/analytics-node#5]
Now everything that depends on analytics-node 0.5.0 fails npm install:

```
deshao (1)~/base> npm install
npm WARN unmet dependency /home/eshao/wsp/kites/src/kites-base/node_modules/kites-util/node_modules/analytics-node/node_modules/request/node_modules/form-data requires mime@'~1.2.2' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
```

As you can see, analytics-node depends on request which depends on form-data which depends on mime 1.2.2, which has gone missing.

**Comment by hankim813** [comment]
Going to close this based on the date of the issue, please let me know if you are still having problems and I'll reopen. Thanks!
