### ISSUE TITLE
Do not overwrite `context.library`

### ISSUE THREAD

**Issue by theoephraim** [segmentio/analytics-node#50]
I am trying to pass through a `platform` value in the amplitude integration, which is pulling its value from `context.library`

This module is setting `context.library` to `analytics-node` even when I pass in a value. You should not override if it a value is provided. It would be better to call `_.defaults` instead of `_.extend`
see: https://github.com/segmentio/analytics-node/blob/master/lib/index.js#L172

**Comment by hankim813** [comment]
@f2prateek

**Comment by f2prateek** [comment]
The right solution would be to fix the amplitude integration so it doesn't get platform from `context.library.name`, but rather `context.os` or something else.

**Comment by f2prateek** [comment]
Also, you should not set a custom library name if you are using this library.

**Comment by f2prateek** [comment]
https://github.com/segmentio/integration-amplitude/issues/9

**Comment by theoephraim** [comment]
Makes sense. Im just trying to get my data over to amplitude the way they need it to show up in the UI.
