### ISSUE TITLE
Flush isn't behaving according to the docs

### ISSUE THREAD

**Issue by nathanpeck** [segmentio/analytics-node#53]
According to the documentation:

```
By default, our library will flush:

The very first time it gets a message.
Every 20 messages (controlled by options.flushAt).
If 10 seconds has passed since the last flush (controlled by options.flushAfter)
```

However the actual implementation resets the timeout every single time an event is enqueued:

https://github.com/segmentio/analytics-node/blob/master/analytics-node.js#L183-L185

What this means is that if you have `flushAt` set to 20, and `flushAfter` set to 10 seconds then each time a message arrives and is enqueued the timeout that controls `flushAfter` is reset to 10 seconds again.

So:

1) A message arrives in queue, and the timer is set for 10 seconds
2) 9 seconds pass, and another message arrives in queue. The timer is reset for another 10 seconds in the future, now 19 seconds since the last flush.
3) 9 seconds pass, another event arrives, and the flush timer is reset again, now triggering at 28 seconds since the last flush.

So with the default settings the queue can be stored for up to 200 seconds before flushing rather than the desired 10 seconds.

The correct behavior would be to set the timer on the first enqueued item, and then leave it as is, so that the next flush happens exactly 10 seconds later. If I have time I'll open a PR to fix this.

**Comment by nathanpeck** [comment]
Opened a PR to fix the problem.

**Comment by hankim813** [comment]
@f2prateek @sperand-io can you guys take a peek here?

**Comment by nathanpeck** [comment]
@hankim813 @f2prateek @sperand-io Any progress or feedback on this? Is the current flush behavior intentional and the docs inaccurate, or vice versa?

**Comment by f2prateek** [comment]
I don't think it's deliberate, just mis-implemented.

**Comment by vadimdemedes** [comment]
Looks like even after @nathanpeck's PR, the docs still won't represent reality.

> The very first time it gets a message.

I can't find any code that does it.

> If 10 seconds has passed since the last flush (controlled by options.flushAfter)

With @nathanpeck's changes, it's not "10 seconds since the last flush", but "flush every 10 seconds". I think renaming `flushAfter` to `flushInterval` would be a correct way to resolve this confusion.

**Comment by vadimdemedes** [comment]
#103 is merged, so the most important bit of this issue is done.

@stevenmiller888 @stephenmathieson what do you think about renaming `flushAfter` to a more accurate `flushInterval`? We can keep `flushAfter` for backwards compatibility until a major release is out.

**Comment by stevenmiller888** [comment]
+1 to renaming. Much clearer

**Comment by vadimdemedes** [comment]
All of this is fixed in master, thanks for reporting @nathanpeck! Going to leave this issue open until a new release is out.

**Comment by vadimdemedes** [comment]
New release is out - https://github.com/segmentio/analytics-node/releases/tag/v3.0.0.
