### ISSUE TITLE
Cannot resolve `uid` module in react-native.

### ISSUE THREAD

**Issue by danscan** [segmentio/analytics-node#55]
`uid` can't be resolved by the react-native packager because its package.json's `main` property had a value of `yes`.  I have a PR open that resolves the issue:  https://github.com/matthewmueller/uid/pull/9.

**Comment by calvinfo** [comment]
Hey @danscan I just removed the `uid` module. I haven't used react-native, but does it properly load modules without a `main` field?

**Comment by gor181** [comment]
Same thing happened to me.

It works in both cases by setting the `main` to `index.js` or by omitting it.
