### ISSUE TITLE
Unable to use this with React Native.

### ISSUE THREAD

**Issue by homanp** [segmentio/analytics-node#58]
When running npm install --save analytics-node and invoking in my RN Project I get the following error:

`Unable to resolve module assert.`

**Comment by calvinfo** [comment]
I haven't checked out react-native's handling of this recently, the library itself is supposed to be compatible with node and browserify. It looks like they don't shim the `assert` module properly, might just require tweaks with packaging?

**Comment by homanp** [comment]
Thanks for the reply. Will look into this and post a solution.

**Comment by anton-aleksandrov** [comment]
@homanp , could you tell, how did you solved this?

**Comment by homanp** [comment]
Hey, I went with a straight obj-c implementation of segment.
