### ISSUE TITLE
No error returned when using with bad write-key

### ISSUE THREAD

**Issue by tonyxiao** [segmentio/analytics-node#59]
```javascript
new Analytics('badKey').identify({userId: "hello", traits: {}}, (err, batch) => {
 if (err) {
    console.log('err', err)
  } else {
    console.log('success')
  }
})
```

The above script will log success instead of err. That's unexpected. `analytics-node` should return error in callback for invalid write key.

**Comment by sperand-io** [comment]
Agreed. Unfortunately, this is a deliberate tradeoff at the API level right now, and not a library issue. The edge is stateless and always returns 200 (like Google Analytics and many other analytics providers). If we implement a way to ping for write key validity, we'll be sure to add that to our libraries!

**Comment by tniemann** [comment]
HI,

how is the process here?
