### ISSUE TITLE
Uncaught Error while using latest version with chrome extension

### ISSUE THREAD

**Issue by benjaminhoffman** [segmentio/analytics-node#60]
working on a chrome extension as found  here: https://segment.com/docs/sources/website/guides/chrome-extension/

step one says to download latest analytics-node library

when I do and require it, I get the following error: `Cannot set property length of [object Object] which has only a getter`

when I revert back to the version found in this chrome extension: https://github.com/segmentio/daydream/blob/master/lib/background/analytics-node.js, everything seems to work fine.

my extension can be found here: https://github.com/benjaminhoffman/segment-demo-extension.  simply swap out the analytics-node file to see the error.

cc @sperand-io

**Comment by vadimdemedes** [comment]
Hey @benjaminhoffman, I've compiled the latest master to a bundle using webpack and been able to load and use your extension. Please try loading the latest version instead. A new release is going to be out soon, but you can compile a bundle from master in the meanwhile.
