### ISSUE TITLE
reset method

### ISSUE THREAD

**Issue by vhmth** [segmentio/analytics-node#61]
Seems like the `reset` method as detailed [here](https://segment.com/docs/sources/website/analytics.js/#reset-logout) is missing. Per Segment's Chrome extension source on-boarding, I am using this lib to `identify` a user when they login but would like to call `reset` when they logged out.

I noticed that https://github.com/segmentio/analytics-node/issues/46 addresses this and then links to https://github.com/segmentio/analytics.js/issues/485, which is `analytics.js`. Should Chrome extension apps be using `analytics.js` instead? If that's the case, the Segment documentation should be updated to reflect that.

**Comment by vhmth** [comment]
https://www.opentest.co/share/b586354059d011e6a1ffdd04f7a207b4

**Comment by stephenmathieson** [comment]
There is no need for a `reset()` method in this library, as it's stateless (it doesn't record/persist user IDs the same way analytics.js does).
