### ISSUE TITLE
Dependency on "brfs" packaged for browserify transform breaks with missing devDependencies

### ISSUE THREAD

**Issue by joshgentry** [segmentio/analytics-node#65]
If `analytics-node` is a dependency of a project that uses browserify in it's build process, it will trigger the need for the `brfs` module which will not have been installed via npm due to being filed under the devDependencies for `analytics-node`.

After an `npm install brfs` in the root project, it's possible to `require('analytics-node')` from within the project without issue.

When the `brfs` module is unavailable the following error occurs during the browserify require step:

```
Error: Cannot find module 'brfs' from '/[...]/node_modules/analytics-node'
Warning: Error running grunt-browserify. Use --force to continue.

Aborted due to warnings.
```

**Comment by timelf123** [comment]
Might make sense to have brfs as a peerDepencency?

**Comment by joshgentry** [comment]
To an extent, I think brfs may make sense as a peerDependency, though that places the burden on the user of analytics-node to install the package separately (as of NPM 3) or list it as their own dependency which might get strange with future updates.

I'd prefer adding it as a regular dependency, but a peerDependency is acceptable imo, other thoughts?

**Comment by vadimdemedes** [comment]
> Might make sense to have brfs as a peerDepencency?

This wouldn't install it on user's project, as @joshgentry correctly pointed out. It will only display a warning message on `npm install analytics-node`.

> I'd prefer adding it as a regular dependency

That way every installation will come with `brfs`, with isn't optimal, of course. It clearly belongs to `devDependencies`.

I'm new to this project and I couldn't trace it to the source of the problem, but why do we even need `brfs`? I can't find any `fs.readFile` calls in `analytics-node`'s code base.

cc @stevenmiller888

**Comment by vadimdemedes** [comment]
If https://github.com/segmentio/analytics-node/pull/104 is going to get merged, the problem will be gone altogether, since it removes `brfs`.

**Comment by vadimdemedes** [comment]
#104 is merged, keeping this open until the next release.

**Comment by vadimdemedes** [comment]
New release is out - https://github.com/segmentio/analytics-node/releases/tag/v3.0.0, which no longer contains a browserify bundle. If you're using a module bundler (webpack/browserify/rollup/etc), `analytics-node` should bundle just fine.
