### ISSUE TITLE
[Intercom] - Integration is missing app_id key

### ISSUE THREAD

**Issue by danieleleoni** [segmentio/analytics-node#69]
Hi guys, I'm trying to integrate intercom via segment into an universal app with React
After first setup I can see that scripts are injected correctly, but widget is not displayed at all.
NOTE that integration is working perfectly, I can see data into debugger, only widget button is missing

After some hours of troubleshooting I noticed that the only way to get it working is to set

```
window.intercomSettings = {
  app_id: "12345", // change with a real ID
}
```

But if I set intercomSettings in this way, all the other value I set with analytics are not saved
For example

```
analytics.identify({
  userId: '019mr8mf4r',
  traits: {
    name: 'Michael Bolton',
    email: 'mbolton@initech.com',
  },
})
```

I already checked secure mode and guest mode
Any idea?

**Comment by f2prateek** [comment]
If you're still having this issue, please write in via https://segment.com/contact.

Your issue also seems to be with analytics.js which is a different library https://segment.com/docs/sources/website/analytics.js/
