### ISSUE TITLE
Unable to resolve dependency modules

### ISSUE THREAD

**Issue by diogoguimaraes** [segmentio/analytics-node#70]
I'm having the following error after adding the `analytics-node` to my `package.json` 

![screenshot_1476290321](https://cloud.githubusercontent.com/assets/8330387/19319108/4a0776a8-90a3-11e6-8b0e-cb664a383723.png)

I'm guessing it may be the `assert` dependency that might be broken. Can you please have a look at it?
I'm using `react-native@0.35.0`.

Thanks.

**Comment by stephenmathieson** [comment]
@diogoguimaraes we don't currently support react-native here, but instead, recommend using either [analytics-ios](https://github.com/segmentio/analytics-ios) or [analytics-android](https://github.com/segmentio/analytics-android).

Alternatively, @tonyxiao created [this repo](https://github.com/tonyxiao/react-native-analytics) which handles both =)
