### ISSUE TITLE
is there an optional callback to `identify()` calls?

### ISSUE THREAD

**Issue by chovy** [segmentio/analytics-node#71]
I'm seeing inconsistent event tracking in intercom. Sometimes track calls show up in intercom with a user and sometimes the user has no events. All the data appears to be going to segment.io, but possibly not in the correct order.

I am curious if its because we call `identify()` and `track()` asynchronously....I noticed `track()` has a callback option but I could not find one documented for `identify()`.

We need something like this:

```
analytics.identify(identifyData, function(err, resp){
 analytics.track(trackingData);
}
```

In our specific use case its for a cli tool written in node. There is no user login or authentication....so we identify the user (uuid hardware id) every time we track a command.

We are currently doing the following which is yielding inconsistent results:

```
analytics.identify(identifyData);
analytics.track(trackingData);
```

**Comment by nabilfreeman** [comment]
Hey @chovy (and everybody here coming from Google)...

I digged through the analytics code and it looks like the identify call does indeed include a callback option:

https://github.com/segmentio/analytics-node/blob/master/analytics-node.js#L53

On a side note, the way I've implemented this to get promises working is

```
return new Promise(resolve => {
    analytics.identify({ userId: user.id }, resolve)
});
```

**Comment by chuckhacker** [comment]
Can you please re-open this?

We immediately track an event after identifying which actually creates a race condition with Intercom like so:

```
POST https://api-iam.intercom.io/messenger/web/events 404 (Not Found)
(index):1 Uncaught (in promise) {"type":"error.list","request_id":"assmschqur36mfnaap2g","errors":[{"code":"not_found","message":"User Not Found"}]}
```

because the user is not found since they haven't been "identified" yet.

**Comment by stephenmathieson** [comment]
Hey @chuckhacker looks like you're using analytics.js, not analytics-node. Their APIs are a bit different. If you're having an issue with it, head on over to https://github.com/segmentio/analytics.js for help.
