### ISSUE TITLE
Upgrade to superagent 2.x

### ISSUE THREAD

**Issue by pkaminski** [segmentio/analytics-node#72]
The `superagent` dependency is currently stuck at `1.8.3`, while there have been significant fixes since.  In particular, the `double callback!` bug is supposed to have been resolved.  I see this warning all over my logs but can't tell if it's an issue in `superagent` `2.3.0` (which my app uses) or just the old bug in `1.8.3` (brought in by `analytics-node`).

**Comment by stephenmathieson** [comment]
#89
