### ISSUE TITLE
How to get an anonymousId ?

### ISSUE THREAD

**Issue by danieleleoni** [segmentio/analytics-node#73]
Hi guys,

it seems that it is not possible to retrieve an anonymousId and moreover userId is required
How can I manage this problem?

I should send an identify event like this
`return analytics.identify({
    anonymousId: 'xxxxxx-xxxxxxxxx-xxxx',
)}`

But `analytics.user().anonymousId()` seems it's not available and userId is required

**Comment by teacii** [comment]
HI,

I investigated this and found that this is an older library.

You can get away with generating a random userId of your own and using it.

There is no user() function in this library.

Hope it helps

Cheers

**Comment by nrser** [comment]
so... that explains the divergent APIs i guess `track({event: <event-name>, properties: <props>})` vs `track(<event-name>, <props>)`... which is pretty much the opposite of what you want these days.

i got the links to this right off their website:

https://segment.com/docs/sources/website/analytics.js/#performance
https://segment.com/docs/sources/server/node/#development

their [analytics.js][https://github.com/segmentio/analytics.js] doesn't seem to include anything about server-side integration.

i've only been playing with this thing for an hour or so, but it's not confidence inspiring :/

**Comment by teacii** [comment]
I agree.
It is sad to see such a tech based company not supporting simplest of platforms in use.

**Comment by f2prateek** [comment]
This is a server side library and does not store the anonymous ID. analytics.js is the client side library that does does store anonymous IDs https://segment.com/docs/sources/website/analytics.js/#retrieving-the-anonymous-id

**Comment by simistern** [comment]
Curious if there is a react-native implementation for getting the anonymous ID in segment/branch?
