### ISSUE TITLE
Provide a test mode or a mock class

### ISSUE THREAD

**Issue by thesmart** [segmentio/analytics-node#75]
Out-of-the-box, there is no supported way to test against Segment's `analytics-node` module without a connection to a Segment server.  In your own tests, you guys startup a server process that listens on localhost to test against.  This isn't a practical solution for consumers, and it's a better practice to provide a mock shim to test against.  Most other libraries support this, please add this functionality.

I think I can work around this by monkey-patching `flush`:
```
analytics.flush = function(fn) {
  process.nextTick(() => { fn(null, []); });
};
```

This is pretty lame though, a supported mock stub would be greatly appreciated.  Thanks.

**Comment by stephenmathieson** [comment]
Yep, not a bad idea. We've got some old code that sends events to a "fake" source when we run our test suite.

I'll add something =D

**Comment by stephenmathieson** [comment]
decided against this. thanks for the suggestion tho!

**Comment by alexpanov** [comment]
@stephenmathieson could you please explain your reasoning?
We would love to have this feature too.

**Comment by stephenmathieson** [comment]
@alexpanov I began putting this together, but then decided the complexity/overhead isn't worth the gain. see https://github.com/segmentio/analytics-node/pull/90#issuecomment-286475234.

**Comment by stephenmathieson** [comment]
fwiw, here's what you could do on your end:

```js
const Analytics = require('analytics-node')
const { NODE_ENV } = process.env
if (NODE_ENV === 'test') { // or w/e
  Analytics.prototype.flush = fn => fn()
}
```

**Comment by alexpanov** [comment]
@stephenmathieson Thank you sooo much! I feel this should be documented somewhere.
Any idea how to do the same thing for the web js library?

**Comment by stephenmathieson** [comment]
> I feel this should be documented somewhere.

I'd gladly merge a PR =)

> Any idea how to do the same thing for the web js library?

I'm not technically maintainer for analytics.js, so I don't want to provide the wrong information... but on my side-projects, I stub out `window.analytics` fully rather than including it on my page. see https://github.com/stephenmathieson/bikeshedding.us/blob/7ac014901afe0b1b189d73e99c75b83b5d30b5ac/src/dev.html#L6-L13 for an example.
