### ISSUE TITLE
Include the Node version in the event somehow

### ISSUE THREAD

**Issue by stephenmathieson** [segmentio/analytics-node#79]
Would be nice for internal metrics to see what versions of node our customers are actually using

**Comment by timelf123** [comment]
Perhaps here https://github.com/segmentio/analytics-node/blob/master/lib/index.js#L171

**Comment by f2prateek** [comment]
Technically Context is strict, and is not recommended to send unspecd fields https://segment.com/docs/spec/common/#context.

Additionally context is for customer facing data. This information would only really be useful for our own analytics.

We'll likely want to use `_metadata` like our a.js library does.

**Comment by stephenmathieson** [comment]
Ah cool, `_metadata` sounds good! Thanks @f2prateek!

**Comment by Dorian** [comment]
@stephenmathieson @f2prateek Ok, fixed that, not sure about the server side handling of the `_metadata` though, e.g. #84
