### ISSUE TITLE
replace TravisCI with CircleCI

### ISSUE THREAD

**Issue by stephenmathieson** [segmentio/analytics-node#80]
We use CircleCI everywhere else, so it'd be nice to not have to worry about the differences between Circle and Travis

Thoughts @segmentio/gateway?

**Comment by f2prateek** [comment]
Travis has out of the box matrix support. Important for us to run checks against different node versions. If we can set that that with circle then 👍 .

**Comment by stephenmathieson** [comment]
Ah right, forgot about that. Looks like there are a few [hacky ways to do it](https://discuss.circleci.com/t/testing-multiple-versions-of-node/542), but no support out of the box...
