### ISSUE TITLE
Remove dependency on request, allow dependency injection

### ISSUE THREAD

**Issue by eshao** [segmentio/analytics-node#9]
Right now, we can't browserify this library because request is incompatible. If you allow the library to take in a dependency, we can pass it request on the server side and https://github.com/iriscouch/browser-request on the client-side. 

This would be helpful because analytics.js also doesn't work with browserify.

**Comment by kevinSuttle** [comment]
Not sure if this is the right thread for this, but it would be nice if this Node library was aware of the client-side snippet. Right now, I have to put in logic in my view template so the snippet gets the right user.

**pseudo-code**
If there is a logged in user (Passport/Express `req.user set to req.app.locals.user`)
don't include `"identify"` in the immediately-invoked set up, and call it separately below, passing the logged-in user's id. 

If there isn't, include `"identify"` in the setup function, but omit the client-side `identify()` call in the snippet.  
```html
{?user}
<script type="text/javascript">
  !function(){var analytics=window.analytics=window.analytics||[];if(!analytics.initialize)if(analytics.invoked)window.console&&console.error&&console.error("Segment snippet included twice.");else{analytics.invoked=!0;analytics.methods=["page"];analytics.factory=function(t){return function(){var e=Array.prototype.slice.call(arguments);e.unshift(t);analytics.push(e);return analytics}};for(var t=0;t<analytics.methods.length;t++){var e=analytics.methods[t];analytics[e]=analytics.factory(e)}analytics.load=function(t){var e=document.createElement("script");e.type="text/javascript";e.async=!0;e.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.com/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(e,n)};analytics.SNIPPET_VERSION="3.0.1";
  analytics.load('{config.segment.writeKey}');
  analytics.page({'name': '{title}'});
  analytics.identify('{user.id}');
  }}();
</script>

{:else}

<script type="text/javascript">
  !function(){var analytics=window.analytics=window.analytics||[];if(!analytics.initialize)if(analytics.invoked)window.console&&console.error&&console.error("Segment snippet included twice.");else{analytics.invoked=!0;analytics.methods=["page", "identify"];analytics.factory=function(t){return function(){var e=Array.prototype.slice.call(arguments);e.unshift(t);analytics.push(e);return analytics}};for(var t=0;t<analytics.methods.length;t++){var e=analytics.methods[t];analytics[e]=analytics.factory(e)}analytics.load=function(t){var e=document.createElement("script");e.type="text/javascript";e.async=!0;e.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.com/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(e,n)};analytics.SNIPPET_VERSION="3.0.1";
  analytics.load('{config.segment.writeKey}');
  analytics.page({'name': '{title}'});
  }}();
</script>
{/user}
```

The extra sucky part is that I only have to call identify on the front-end because the integrations I'm using only work in the browser. :tada:

**Comment by mmahalwy** [comment]
Any luck with this?

**Comment by gilbarbara** [comment]
Hey,
I'm trying to implement this with browserify and I had to tweak my configuration for this 2 years old issue.
Discouraging :-1:

**Comment by calvinfo** [comment]
Sorry about that! We've actually removed request, moved to superagent, and taken steps to make sure the lib is browserify compatible. What issues did you run into?

Since this issue is fairly old, and we've dropped `request` support, I'm going to close this for now.
