### ISSUE TITLE
Can I promisify analytics-node functions?

### ISSUE THREAD

**Issue by johntangma** [segmentio/analytics-node#93]

**Comment by pdkn** [comment]
This is how we are doing it
```
var promise = new Promise((resolve, reject) => {
      this.segmentClient.track( analyticsParams, (err, batch) => {
           if (err) {
               reject();
           }
           resolve();
       });
});

return promise;
```

**Comment by stephenmathieson** [comment]
@pdkn's solution looks almost perfect. to maintain compatibility with the API, we should resolve the response and reject with any errors:

```js
function track (params) {
  return new Promise((resolve, reject) => {
    analytics.track(params, (err, res) => {
      if (err) {
        reject(err)
      } else {
        resolve(res)
      }
    })
  })
}
```

hope this helps!

**Comment by villeodell** [comment]
This works for anyone wanting to promisify with [util.promisify](https://nodejs.org/api/util.html#util_util_promisify_original):

```
const analytics = require('analytics-node')(SEGMENT_KEY);
  
const { promisify } = require('util');
const [ identify, track] = [ analytics.identify.bind(analytics), analytics.track.bind(analytics)].map(promisify);
```

Note the  .bind is required to explicitly set the context of the analytics-nodes functions which use .this

- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_objects/Function/bind
- https://stackoverflow.com/questions/45064380/function-works-but-not-when-util-promisify-used#answer-45064465
