### ISSUE TITLE
How to delete the user from Mixpanel?

### ISSUE THREAD

**Issue by teckays** [segmentio/analytics-node#97]
I am trying to implement a `track` event in order to delete the user from Mixpanel. The Mixpanel documentation says:
```
// This removes the user 13793 from Mixpanel
{
    "$token": "36ada5b10da39a1347559321baf13063",
    "$distinct_id": "13793",
    "$delete": ""
}
```

What I have tried so far:
```
.track({
      userId: userId,
      event: 'User - Delete',
      properties: {
        distinct_id: userId,
        $delete: ''
      }
    })
```

But that doesn't seem to delete the user, it simply sends an event to Mixpanel.

**Comment by stephenmathieson** [comment]
To be 100% honest, I have no idea if you're able to do that via analytics-node (or even Segment). Deleting a user seems like something you'd do directly in Mixpanel, not from your node app.

/cc @hankim813 and @sperand-io - you fellas probably know better than I do here.

**Comment by hankim813** [comment]
@stephenmathieson yes -- we never were in the business of _deleting_ data in 3rd party tools. We have no mappable api for that. They should delete within the UI.
