### ISSUE TITLE
Cannot access Node server logs  at appboy 

### ISSUE THREAD

**Issue by bipin000** [segmentio/analytics-node#99]
Hi,

I am trying to get all my node server logs from segment to Appboy, but there is a conflict doing that while  Appboy does not support arrays or nested objects for custom track event properties [https://segment.com/docs/integrations/appboy/#track](https://segment.com/docs/integrations/appboy/#track) and this api only push data in json object format so therefore I cannot get my node server logs in appboy through this api

**Comment by stephenmathieson** [comment]
I do not understand the issue here. If you enable Appboy, you should be able to send it events via this library (assuming it's a server-side integration... I don't recall if it is or not).

Can you see events showing up in your (segment) debugger from the calls you're making?

**Comment by bipin000** [comment]
yes the events are being captured on segment but not pushed to appboy server from segment

**Comment by stephenmathieson** [comment]
If you're seeing events in your debugger but not Appboy, it's not an issue with this library.

You could have invalid settings (the most common Appboy error), or be sending something Appboy doesn't want. It's hard to debug without more context, but I'm sure this isn't an issue with analytics-node itself.

I'm going to close this for now. If you need more help figuring this out, feel free to message friends@segment.com. Someone should respond pretty quickly :)

**Comment by bipin000** [comment]
This issue resolved, the problem was with the api key I added on the segment for appboy which was with additional space in front and was therefore not able to push log from server to appboy.
